### ISSUE TITLE
Frontend. Link from context menu always leads to last screenshot

### ISSUE THREAD

**Issue by Elverslane** [Visual-Regression-Tracker/Visual-Regression-Tracker#10]
Case: 
1. Write 3+ tests on difference pages and launch it
2. Go to web and try open any of table row with context menu "Details" (see screenshot)
3. All of tests details will contains screenshot of last made test

<img width="1668" alt="Снимок экрана 2020-05-22 в 18 03 53" src="https://user-images.githubusercontent.com/17493900/82682107-65123000-9c57-11ea-8d36-5004ad986381.png">

But its ok if click on table row itself

**Comment by pashidlos** [comment]
thanks for the ticket!
fixed in latest release!
