### ISSUE TITLE
VRT Status is null with appium dependency 

### ISSUE THREAD

**Issue by Ankit7891** [Visual-Regression-Tracker/Visual-Regression-Tracker#105]
Virtual Regression java sdk  is working fine with Selenium, Selenide but when i am trying to add appium dependency. I am getting Status as NULL. 

### **ERROR**:   io.visual_regression_tracker.sdk_java.TestRunException: Status is null

I could not find any error in docker logs. Many jars were common in appium dependency so I removed all duplicate jars eg commons-lang3-3.9.jar, guava-25.0-jre.jar,okhttp-3.11.0.jar.  I have added only following jars which were needed to launch the IOS driver .  
Please find attached screenshot 

<img width="563" alt="Screenshot 2020-08-24 at 10 33 56 AM" src="https://user-images.githubusercontent.com/70129558/91069978-b9acb900-e653-11ea-8f78-d77a92b88822.png">

### CODE 

<img width="1047" alt="Screenshot 2020-08-24 at 8 51 48 PM" src="https://user-images.githubusercontent.com/70129558/91070084-e5c83a00-e653-11ea-8929-4695a9f46809.png">

### **Docker**

<img width="1203" alt="Screenshot 2020-08-24 at 8 49 44 PM" src="https://user-images.githubusercontent.com/70129558/91070125-f678b000-e653-11ea-919f-83979b508b11.png">

**Comment by pashidlos** [comment]
hi @Ankit7891 
thanks for submitting the ticket! 

this looks like dependency conflict within the project 
please, provide sample project with those dependencies

**Comment by Ankit7891** [comment]
Hello Pavel 

Please find zip of the project . I have kept extra jars in JARS folders . Test case related to appium are in test case.java . You may need to update UDID and bundle id of this the java file 

[https://github.com/Ankit7891/samplecode](url)

**Comment by pashidlos** [comment]
link is broken, I guess it's this one https://github.com/Ankit7891/samplecode
could you push it as code and not like zip file?

**Comment by Ankit7891** [comment]
Sorry for the broken link...I have pushed the code again . 
U take the clone using : git clone https://github.com/Ankit7891/examples-java-master.git
git URL : https://github.com/Ankit7891/examples-java-master

FYI..I have kept extra jars in JARS folders . Test case related to appium are in test case.java . You may need to update UDID and bundle id of in the java file

**Comment by pashidlos** [comment]
try with new `4.0.2` version https://github.com/Visual-Regression-Tracker/sdk-java/releases/tag/4.0.2
also, why are you putting jars manually instead of adding gradle dependency to appium ?
```
compile group: 'io.appium', name: 'java-client', version: '7.3.0'
```

**Comment by Ankit7891** [comment]
It was not working when I tried adding appium dependency using gradle.
Some jars were common in VRT and appium like commons-lang3-3.9.jar, guava-25.0-jre.jar,okhttp-3.11.0.jar so tried to add un common jars manually 

I will check with 4.0.2 version

**Comment by Ankit7891** [comment]
I am getting same error with 4.0.2 version.

**Comment by pashidlos** [comment]
could you confirm that manually added jars are replaced with appium dependency?
also please, provide full stucktrace

**Comment by pashidlos** [comment]
@Ankit7891 there are at least two issues here:
- backend error was not handled properly - issue created #109 
- appium somehow creates `base64` with new line characters that causing issue above - this is issue on appium side https://github.com/appium/appium/issues/14684

temp workaround

```
((TakesScreenshot) driver).getScreenshotAs(OutputType.BASE64).replace("\n", "")
```

**Comment by pashidlos** [comment]
base64 format with new line character will be handled in scope of https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/110

**Comment by Ankit7891** [comment]
Thank you . Thanks a lot . I guess it is failing was stuck due to base64 issue .

**Comment by pashidlos** [comment]
Thank you for making project better!
