### ISSUE TITLE
Can we make it so the test continues on screenshot failure and reports the failures at the end of the test? 

### ISSUE THREAD

**Issue by danferk** [Visual-Regression-Tracker/Visual-Regression-Tracker#108]
I have a test that as multiple screenshots. If the first screenshot happens to fail it does not continue on with the rest of the test like it would if you used the built-in “cy.screenshot” option. Is there away to have it continue with the test even if it has a screenshot fails and report the failures at the end.

**Comment by pashidlos** [comment]
@danferk it's implemented already 
let me know if it suits your needs
