### ISSUE TITLE
The images on VRT:8080 still running after they passed!

### ISSUE THREAD

**Issue by Thanoonazad** [Visual-Regression-Tracker/Visual-Regression-Tracker#113]
The images on VRT:8080 still running after they passed when I run it locally!

I get a 2 different buildId on cli is the same but on VRT is different 

![image](https://user-images.githubusercontent.com/45563133/92090972-657ea300-edd0-11ea-9f2f-fc03eb13f4b1.png)

![image](https://user-images.githubusercontent.com/45563133/92091054-7c24fa00-edd0-11ea-89f6-189cb5e0a357.png)

**Comment by pashidlos** [comment]
@Thanoonazad could you clarify what integration you are using? 
depending on that you need to call method that stops `vrt` after all tests are done 
the same as you are starting the build before the tests

**Comment by Thanoonazad** [comment]
@pashidlos I'm using the agent-cypress library.
(https://www.npmjs.com/package/@visual-regression-tracker/agent-cypress)

I tried to start the example: https://github.com/Visual-Regression-Tracker/examples-js/blob/master/agent-cypress/cypress/integration/example.spec.js

this is the result of the example: ![image](https://user-images.githubusercontent.com/45563133/92099143-746a5300-edda-11ea-8491-4ed78db7c3d0.png)




I also did try my own example:
`/// <reference types="cypress" />
/// <reference types="@visual-regression-tracker/agent-cypress/dist" />
describe('Visual Regression Tracker', () => {
    it('VRT', () => {
      cy.visit('http://localhost:1237/')
      /cy.wait(500)
      cy.vrtStart();
      cy.wait(500)
      cy.vrtTrack("home-page");
      cy.wait(500)
      cy.vrtStop();
      cy.wait(500)
    });
  });`

It did work fine without the another buildID but the build is still running!
![image](https://user-images.githubusercontent.com/45563133/92100377-0888ea00-eddc-11ea-82a1-9a2df9dfd748.png)

![image](https://user-images.githubusercontent.com/45563133/92100460-1fc7d780-eddc-11ea-8f33-af1267e045a8.png)

**Comment by pashidlos** [comment]
@Thanoonazad builds that were not properly stopped during test execution or due to build failure could be stopped manually 
hover build and click on more button -> stop build

could you confirm that newly created builds are being properly closed?

**Comment by Thanoonazad** [comment]
@pashidlos So I did stop my docker-compose and started again:

After I approve the baselineimage to referenceimage the buildID is still loading in the VRT-UI: ->

![image](https://user-images.githubusercontent.com/45563133/92103719-a2529600-ede0-11ea-8111-762a4f3b1d20.png)

It's possible the stop the buildID: BUG: Why it is still loading after it already passed?

![image](https://user-images.githubusercontent.com/45563133/92103959-f52c4d80-ede0-11ea-930a-2d3bd7591ed7.png)



After stopping it:
![image](https://user-images.githubusercontent.com/45563133/92104093-26a51900-ede1-11ea-9b8b-3c64847d161b.png)

**Comment by Thanoonazad** [comment]
This is from now after I did approve the image!
![image](https://user-images.githubusercontent.com/45563133/92104549-c498e380-ede1-11ea-8403-59e6e2902b1a.png)

**Comment by Thanoonazad** [comment]
@pashidlos  So the problem now I think if I have an image and has no reference on VRT it will keep loading and it has to stop manually.

**Comment by pashidlos** [comment]
@Thanoonazad could you make sure that the code related to stopping the build is being executed even if exception arise? 
to make the build stop it's important to execute `cy.vrtStop();`
are you using this example already?
https://github.com/Visual-Regression-Tracker/examples-js/blob/master/agent-cypress/cypress/integration/example.spec.js

**Comment by Thanoonazad** [comment]
@pashidlos I run this example as before:
![image](https://user-images.githubusercontent.com/45563133/92106540-d465f700-ede4-11ea-9428-e85e132eacd3.png)
They are empty:
![image](https://user-images.githubusercontent.com/45563133/92107017-6c63e080-ede5-11ea-921a-25a1621a9f50.png)


with my example:
![image](https://user-images.githubusercontent.com/45563133/92107322-dda39380-ede5-11ea-8b0c-538a72938c0c.png)

not empty and it is still running(loading).
![image](https://user-images.githubusercontent.com/45563133/92107153-9f0dd900-ede5-11ea-913b-4c213dda122b.png)

**Comment by pashidlos** [comment]
@Thanoonazad the problem here is that test stops being executed since exception is thrown 
move setup and teardown methods into before/after hooks
this way they are executed even if test fails 
```js
before(() => {
  cy.vrtStart();
});

after(() => {
  cy.vrtStop();
});
```

**Comment by pashidlos** [comment]
@Thanoonazad is this still an issue for you?
