### ISSUE TITLE
[Codeceptjs] instead of error message get an 500 error

### ISSUE THREAD

**Issue by Elverslane** [Visual-Regression-Tracker/Visual-Regression-Tracker#117]
if in main VRT project not increase value of `BODY_PARSER_JSON_LIMIT` get an 500 error after tests running:

`[Wrapped Error] "Request failed with status code 500"`

`I vrt track "Default"`
  `  › Screenshot is saving to /node_modules/@visual-regression-tracker/agent-codeceptjs/dist/Default-1599130117292.png`
   ` [1] Error | Request failed with status code 500`
   ` Emitted | step.failed (I vrt track "Default")`
   ` Emitted | step.finish (I vrt track "Default")`
    `[1] Error | Error: [Wrapped Error] "Request failed with status code 500"`
    `Emitted | step.failed (I vrt track "Additional options",`
`{"os":"windows","device":"device","browser":"chrome","diffTollerancePercent":13})`
  `  Emitted | step.finish (I vrt track "Additional options",`
`{"os":"windows","device":"device","browser":"chrome","diffTollerancePercent":13})`
 ` [1] Error | Error: [Wrapped Error] "Request failed with status code 500"`
  `  [1] Starting <teardown> session`
   ` Emitted | test.failed ([object Object])`
   ` Emitted | test.finish ([object Object])`
    `[1] <teardown> Stopping recording promises`

docker-compose logs
```
Nest] 17   - 09/03/2020, 1:29:10 PM   [ExceptionsHandler] request entity too large +9633002ms
PayloadTooLargeError: request entity too large
```

**Comment by RyKilleen** [comment]
I'm also receiving this, from a pretty straight-forward test case (Load site, take screenshot.)

**Comment by RyKilleen** [comment]
So this relates to NestJS's config, which can be modified from the .env file.

The value that needs to change is `BODY_PARSER_JSON_LIMIT`

By default, it's set to 1mb. That doesn't seem sufficient, or the body that's being parsed is unusually large for some reason. I set mine to 500mb to be ridiculous.

**Comment by pashidlos** [comment]
Next version will contain error message with stacktrace instead of just 500
this will be done in scope of https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/128
so this is more the issue of not descriptive error
