### ISSUE TITLE
Create install/update script 

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#120]
scrip should be able to follow installation steps with ability to parametrise configuration 
It should receive URL param to patch `REACT_APP_API_URL` and `APP_FRONTEND_URL` in `.env` file 
and params for api/ui/migration image  in `docker-compose.yml`
if possible add checks if docker and docker-compose are installed

## Install scenario
download default `docker-compose.yml`
download default `.env`
patch `.env`
start

### Update scenario
stop containers 
patch `docker-compose.yml`
start

**Comment by alexromanov** [comment]
I'll take a look.

**Comment by alexromanov** [comment]
As for update scenario. I think it is mote suitable to give an update option to the user. For a full update - it is possible to re-run setup script. For a custom image update - it can be done manually and saved in version control system - so it's trackable.

**Comment by dcrowe** [comment]
I've had a go at completing Alex's work in #159.
