### ISSUE TITLE
Python. Add playwright agent

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#129]
Python playwright is already out
https://github.com/microsoft/playwright-python

JS example:
https://github.com/Visual-Regression-Tracker/agent-playwright

**Comment by dcrowe** [comment]
I'll put up my hand for this one.

**Comment by pashidlos** [comment]
@dcrowe you could use this repo 
https://github.com/Visual-Regression-Tracker/agent-playwright-python

**Comment by dcrowe** [comment]
I was thinking of putting it into the python-sdk package. Python packages have support for optional "extras" that I think would be suitable here.

e.g.
`pip install visual_regression_tracker` gives you vanilla VRT with minimal dependencies
`pip install visual_regression_tracker[playwright]` gives you VRT with playwright integration

I think this has the following benefits:
* less work for us hopping between repos
* less work for users who only have to find one package

**Comment by dcrowe** [comment]
I've put together an initial implementation in this PR: https://github.com/Visual-Regression-Tracker/sdk-python/pull/17

Would you still prefer to keep it in a separate package/repo?

**Comment by pashidlos** [comment]
didn't know it's possible :)
honestly it's headache to support multiple JS agent repos so I don't want to have the same if there is such an option!

**Comment by dcrowe** [comment]
👍

**Comment by pashidlos** [comment]
@dcrowe great job!

released in `4.6.0`

https://twitter.com/VisualReTracker/status/1331639937259745284
