### ISSUE TITLE
Add confirmation delete screenshot and test run

### ISSUE THREAD

**Issue by savostyanovmm** [Visual-Regression-Tracker/Visual-Regression-Tracker#131]
Add confirmation delete screenshot and test run.
![Visual Regression Tracker 1](https://user-images.githubusercontent.com/70155382/93322193-b7d1b200-f81b-11ea-83ae-4a61f0c42000.png)
![Visual Regression Tracker 2](https://user-images.githubusercontent.com/70155382/93322197-b86a4880-f81b-11ea-8ee7-d3e4fa77ceb2.png)

**Comment by pashidlos** [comment]
Gonna be a part of `4.4.0` release
