### ISSUE TITLE
Backend. Clean up old screenshots

### ISSUE THREAD

**Issue by aartikov** [Visual-Regression-Tracker/Visual-Regression-Tracker#135]
Visual regression testing generates a lot of screenshots. Store them all during unlimited amount of time is demanding.
VRT should provide a way to clean up old screenshots.

**Comment by priyankachaturvedi30** [comment]
Hey, This is something similar to what I was looking for. However, my concern is that we should preserve baselines and then do the cleanup. Any thoughts ?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 you are right, baseline history need to stay untouched 
I guess we could clean up test runs that are not related to baseline history ex in `failed` `unresolved` and `ok` statuses

**Comment by pashidlos** [comment]
@suratdas thanks for contribution 
gonna be released as part of version `4.15.0`

**Comment by aartikov** [comment]
@suratdas @pashidlos That is awesome! Thank you!
