### ISSUE TITLE
How to see the API request logs on the console?

### ISSUE THREAD

**Issue by wagoid** [Visual-Regression-Tracker/Visual-Regression-Tracker#154]
When running the containers with the default setup, I only see the initial app's logs on `docker-compose` output. After logging in on the UI, creating builds and similar things the logs of the `api` service don't change.

Is there any additional setup that needs to be done in order to see request logs on the stdout?

I'm not sending any details about my run because I just did the default setup from the readme, but happy to add any details that may be required!

**Comment by pashidlos** [comment]
there are no info logs implemented on backend
only some errors are logged into console 

please, describe what kind of logs you would like to see and why

**Comment by wagoid** [comment]
Hi @pashidlos, thanks for the quick response! I was expecting to see request logs, but I'll do that in the proxy level instead. So I think everything is fine from my end. Will close this issue :smiley:
