### ISSUE TITLE
Tests fail correctly, but diff image not shown in acceptance UI

### ISSUE THREAD

**Issue by DigTheDoug** [Visual-Regression-Tracker/Visual-Regression-Tracker#166]
**Details:**
Local docker 2.5.0.1 on OSX, running on new project after following wiki/guidelines. Using Cypress as runner.

`vrt.json`
```json
{
  "apiUrl": "http://localhost:4200",
  "project": "my-test",
  "apiKey": "x",
  "branchName": "main",
  "enableSoftAssert": true
}
```
**What happens:**
When I instigate changes to cause a test failure, the tests correctly identify a change, but in the interface to show the changes the actual diff image (with the red highlighting) is not shown and instead I see a "No image available" placeholder. The baseline and actual images show fine, so it is just the diff when toggled that does not show.

![Screen Shot 2020-12-08 at 12 38 04 PM](https://user-images.githubusercontent.com/1428256/101520349-5caee780-3952-11eb-9e5a-8e3785d08b2f.png)

I don't see any errors output to the terminal from the service when running tests, so nothing else stands out. Any ideas what might be causing this? Do you need anymore info from me?

**Comment by pashidlos** [comment]
@DigTheDoug could you make a full page screenshot? 
I have a theory that new image resolution is different from baseline thus pixel by pixel comparison is not possible
you could see the real image size near branch name in test details modal 
please, let me know if this is the case or not

**Comment by DigTheDoug** [comment]
Sure, thanks for the quick reply. Here's a few screenshots as well as the code I'm using to test because I am doing some sizing related tests:

```js
const appConfig = require('../../application.json');
const basePath = appConfig.frontend_path;

const sizes = ['iphone-6', 'macbook-15'];

describe('Example', () => {

  before(() => {
    cy.vrtStart();
  });
  
  after(() => {
    cy.vrtStop();
  });

  sizes.forEach((size) => {
    describe(`for ${size}`, () => {
      beforeEach(() => {
        cy.viewport(size);
        cy.server();
      });

      it('should bring up the home page.', () => {
        cy.visit(basePath);
        cy.document().its('location.pathname').should('eq', basePath);
        
        cy.vrtTrack(`should bring up the home page - ${size}`);
      });
    
      it('should bring up the video page', () => {
        cy.visit(`${basePath}video/`);
        cy.document().its('location.pathname').should('eq', `${basePath}video/`);
        cy.contains('Loading').should('not.be.visible');

        cy.vrtTrack(`should bring up the video page - ${size}`);
      });
    });
  });
});
```

![Screen Shot 2020-12-09 at 9 09 27 AM](https://user-images.githubusercontent.com/1428256/101640607-b53bbe80-39fe-11eb-9978-e14eefbce0ec.png)
![Screen Shot 2020-12-09 at 9 09 49 AM](https://user-images.githubusercontent.com/1428256/101640610-b53bbe80-39fe-11eb-8a14-743e407b276f.png)
![Screen Shot 2020-12-09 at 9 09 56 AM](https://user-images.githubusercontent.com/1428256/101640611-b5d45500-39fe-11eb-9e4a-32fd84e0b6aa.png)

Looks like your theory is correct. Changing the text in this case changes the height of the capture, making the images different sizes. Is there a way to force capture size or something similar that would still allow it to work, or at that point would every pixel past that point just be different anyways so it's likely not useful? Unfortunately it seems fairly common that a visual diff would result in a different capture size. If not possible, maybe just a message that says 'Actual image size differs from baseline' to be more clear?

For some context I'm somewhat familiar with some other Cypress plugins that do a similar thing (like https://github.com/meinaart/cypress-plugin-snapshots and https://github.com/jaredpalmer/cypress-image-snapshot) which do 'work' with different image capture sizes but in practice they end up a bit too flaky and CI blocking to be truly useful. We use Chromatic for our components and I like the flow of a post-build separate acceptance UI and have been keeping my eye out for a similar entire page or application regression tool.

Anyways, thanks and let me know if there's anything else I can provide or do.

**Comment by DigTheDoug** [comment]
Additionally, as an example, here's the diff from one of the above plugins when I changed the header from an `h1` to an `h2` and from `Home` to `Home 2`. Usefulness is debatable, but it at least does provide something to clue me into the change.
![home spec-undefined](https://user-images.githubusercontent.com/1428256/101642825-70fded80-3a01-11eb-976f-1af9f899a2ff.png)

**Comment by pashidlos** [comment]
@DigTheDoug thanks for your input!

>Is there a way to force capture size or something similar that would still allow it to work

as we support all cypress options you could pass `clip` property  into `vrtTrack` to frame image
still the best option is to have a full control over system under test - make content of the pace controllable (ex intercept request and put needed payload to render on page)

>If not possible, maybe just a message that says 'Actual image size differs from baseline' to be more clear?

I think it's an awesome idea! 
feel free to create a ticket for it!

>do 'work' with different image capture sizes

it's possible to implement this logic, but it requires image resizing that takes more resources and at the end do not provide repeatable output

>We use Chromatic for our components and I like the flow of a post-build separate acceptance UI and have been keeping my eye out for a similar entire page or application regression tool.

I'm using cypress + https://github.com/bahmutov/cypress-react-unit-test for that 
this way I have complete control over data from server
