### ISSUE TITLE
Unable to access frontend app by default on http://localhost:8080

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#179]
I followed the setup of Visual Regression Tracker as stated on https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker.  I got the credentials after doing docker-compose up, but for some reason, I am unable to access the application on http://localhost:8080. @pashidlos Can you help me want I might be missing!  (Setup is done on Windows machine)

**Comment by pashidlos** [comment]
@priyankachaturvedi30 thanks for rising the ticket!
could you share what error messages are you getting in browser console and/or logs from docker?

**Comment by priyankachaturvedi30** [comment]
I actually was able to access the application, but I see no dashboard or UI after login (Just a blank screen is displayed on UI)
![image](https://user-images.githubusercontent.com/50797731/104165826-eb19fb80-541f-11eb-8958-33350dc35f43.png)

Makes me curious as to how can I explore more from a tool perspective. For instance, if I want to add a demo screenshot and expore the capabilities that the tool offers, how can I do that?

**Comment by priyankachaturvedi30** [comment]
I do see some errors on the browser console, Please have a look - 
![image](https://user-images.githubusercontent.com/50797731/104166295-9460f180-5420-11eb-87c2-9039ed2ddd24.png)

**Comment by priyankachaturvedi30** [comment]
@pashidlos : Can you help me proceed as to how can I add a demo screenshot and explore the capability that is offered by this tool?

**Comment by pashidlos** [comment]
>I actually was able to access the application, but I see no dashboard or UI after login.

you should see list of projects with already created `Default project` after you are authorised 
could you check in case there are any errors in browser console as there are non in docker logs?

>Makes me curious as to how can I explore more from a tool perspective. For instance, if I want to add a demo screenshot and expore the capabilities that the tool offers, how can I do that?

you could upload images via integration libraries depending on language you are using
please, check repos with examples and after changing `apiKey` they should work out of the box

**Comment by priyankachaturvedi30** [comment]
This works well for me! Thanks much 👍
