### ISSUE TITLE
Integration of VRT with Existing BDD framework 

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#182]
@pashidlos : I was looking for something which can help me do visual validation for my application. While browsing, I came across the Visual Regression tool; which looks like a fit to my requirement. Have installed it on my local using docker. Tried my hands on with test Data and the tool looks promising. However, I am curious to understand the integration of tool with my existing bdd framework. As I understand the flow, we need to start the vrt session (vrt.start), then do a screencapture (vrt.track) and then compare and close the vrt session (vrt.close). However my existing automation scripts are already launching the browser and performing validation, what I need is to understand how can I possibly inject the vrt script (start-track-stop) at runtime in an already launched browser session where I want to do visual tests. Some sort of API call that i can invoke or maybe something on similar lines that can help me invoke the vrt session inside the existing one. Please suggest.

**Comment by pashidlos** [comment]
@priyankachaturvedi30 thanks for your interest!
What is the framework you are using?
Basically the flow you already described
In before all tests hook you need to create VRT instance and call `start` method

Depending on your framework there should be a mechanism to store globals

Then this VRT object needs to be passed down to your tests (or retrieved from globals) in order to call `track`

**Comment by priyankachaturvedi30** [comment]
Great! Thanks for the inputs @pashidlos . I would be trying to integrate it using the steps you provided 👍 
Also, there was one more feature around which I wanted to seek your inputs. Is there a possibility by any chance to integrate something like **Include Area** (which would work as opposite of Ignore Area feature) ? The feature would be tremendously helpful in cases where say suppose there is a graph on my page and everything else is dynamic and I want to visually verify only that graph component, so it would be very handy to just draw an Include Area around that graph component and rest all gets ignored for visual verification? Just thinking out loud! Please share your thoughts on the same. Much Appreciated !
![image](https://user-images.githubusercontent.com/50797731/104882234-b8748380-5988-11eb-9740-1e08be6fd33e.png)

**Comment by pashidlos** [comment]
@priyankachaturvedi30 I guess it's covered here #91
so far it's possible to achieve by making image of needed element instead of full page

**Comment by priyankachaturvedi30** [comment]
okh great! So I think this enhancement is WIP for you, until then we can limit the screenshot size to focus on a particular image of interest.
