### ISSUE TITLE
Approve all button to only approve filtered images

### ISSUE THREAD

**Issue by benquinteros** [Visual-Regression-Tracker/Visual-Regression-Tracker#185]
Would be great if approve all could only approve the filtered images from the dropdowns ( e.g by OS, Browser ).

**Comment by pashidlos** [comment]
@benquinteros thanks for your request!
Sounds like bulk operations with list of items when you select some from list and make action
Do you have any ideas how it could looks like in terms of design?

**Comment by benquinteros** [comment]
![Screen Shot 2021-01-22 at 10 08 52 am](https://user-images.githubusercontent.com/11510971/105423588-ebc15600-5c99-11eb-819f-051eb87db6aa.png)

Something along the lines like this. 

The approve all operation is quite expensive, especially when you have a new build with 100's of images, ideally that would be the problem to solve, but this could help that problem in the short term.

Thanks! :)
