### ISSUE TITLE
Automatically approve new baseline build if changes match an approved branch build

### ISSUE THREAD

**Issue by benquinteros** [Visual-Regression-Tracker/Visual-Regression-Tracker#190]
IMU branch approvals only approve the changes for that branch against the baseline. 

When merging changes a new baseline build is created with the changes having to be re-approved again. 

Is this understanding correct and if so should there be an option to achieve the title ^^

Cheers

**Comment by pashidlos** [comment]
@benquinteros that could for sure improve the flow
when we merge `feature`  into `master` branch
and `master` doesn't match to `feature` baseline
we could try checking if there is `feature` baseline is present among recently merged branches [like this](https://stackoverflow.com/questions/226976/how-can-i-know-if-a-branch-has-been-already-merged-into-master)

let me try investigating this for next version
