### ISSUE TITLE
Uniquely Identify Project + Build Id in Dashboard

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#191]
Suppose I have two projects in my VRT Dashboard: **TestProject1** and **TestProject2**. Now If I execute tests with ciBuildId as **Build1** for TestProject1 then I see images been captured for TestProject1. Now, If I try to execute the test with ciBuildId as **Build1** for TestProject2, then also the images get added in TestProject1 and not in TestProject2 (Since the build name is the same in both cases). Even when I try to filter the project name from dashboard for TestProject2 it says - No builds. Shouldn't the association be based on Project+BuildId and not just BuildId? I strongly feel this should be corrected. Please let me know if I am missing something. @pashidlos

**Comment by pashidlos** [comment]
@priyankachaturvedi30 you are right!
right now ciBuildId should be unique within all projects 
this was reported here #183 and will be released in next version
