### ISSUE TITLE
Flexibility of verifying just the layout and not content

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#196]
@pashidlos : I was exploring more fronts of visual testing as a whole and discovered a use case where I had a table structure with randomly generated data. However, I was only interested in verifying the layout of the table structure irrespective of the data it holds (Attached Image for reference). So is there a way through which I can compare the layouts (i.e. structure) of the baseline and actual images? For such a case it should just validate the alignment and relative position of all elements on the page, such as buttons, menus, text areas, paragraphs, images, and columns. It should ignore the content, color, and other style changes between the pages. Any thoughts?
![image](https://user-images.githubusercontent.com/50797731/106479171-084a6300-64d0-11eb-8c21-1eccd61f209c.png)

**Comment by pashidlos** [comment]
@priyankachaturvedi30 unfortunately having random data will cause noise in image comparison 
ideal approach is to have full control over it by mocking as example
it'll allow you first to make sure that all of needed cases are checked and make image stable as well 
in case it's needed to assert layout only you could try tools like http://galenframework.com/ 
make sure that random data doesn't change layout as well

**Comment by priyankachaturvedi30** [comment]
@pashidlos One more thing around the verification standpoint. There can be some changes that are not visible to the human eye like - anti-aliasing changes, minute rendering changes due to different graphic cards on different machines etc. As I see it VRT does a pixel to pixel comparison, is there any way we can ignore false positives caused because of above mentioned cases ?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 yeah, take images only inside reproducible environment (ex docker)

**Comment by priyankachaturvedi30** [comment]
Hi @pashidlos, I tried taking screenshots on the same environment without changing anything, but as I mentioned above, there were few anti-aliasing changes that caused my tests to fail -- (Created false positives for my run). I believe this is something that we should try to ignore or consider while doing a comparison. Maybe some toggle through which we can control if we want to ignore such rendering changes or not. Attaching screenshot of the use case for your reference. Please suggest.
![Anti-Aliasing_Run1](https://user-images.githubusercontent.com/50797731/107607646-d10e4b80-6c5f-11eb-8a1a-06f9e075947d.png)
![Anti-Aliasing_Run2](https://user-images.githubusercontent.com/50797731/107607674-e2575800-6c5f-11eb-88b5-cc746b2c658f.png)

**Comment by pashidlos** [comment]
@priyankachaturvedi30 based on screenshot I could assume that it's not general AA issue (as some text and other plot would be affected)
looks like right graph is moving and make this noise 
you'll need to freeze animation or in worst case ignore whole region
