### ISSUE TITLE
Build. Add editing for ciBuildId

### ISSUE THREAD

**Issue by suratdas** [Visual-Regression-Tracker/Visual-Regression-Tracker#197]
Once we run tests through any CI (e.g. Jenkins), we are able to tag builds with our custom tag **after the build is finished** (see image below). We should have something similar for VRT as well so that we can keep Jenkins run and VRT run in sync with similar post-run tags and it will be easy to relate one another with the tag. 
![image](https://user-images.githubusercontent.com/9042580/106503890-1326d880-647b-11eb-9dbc-3c39c3fd7d5a.png)

We should have another option to add tags in addition to Delete
![image](https://user-images.githubusercontent.com/9042580/106504551-f0e18a80-647b-11eb-8f27-3863c6caef78.png)

**Comment by pashidlos** [comment]
@suratdas is it something different from `ciBuildId` that you could set while starting new build?
or you would like to edit this field via frontend?

**Comment by suratdas** [comment]
Yes, it is the same as ciBuildId but this should be editable later from the frontend after the run. In fact, I am thinking I should be able to add it from the frontend at any time even if it was not provided during the build. That will make it easy to refer when the build number grows.

**Comment by suratdas** [comment]
@pashidlos I will work on this ticket.

**Comment by pashidlos** [comment]
@suratdas thanks for contribution!
