### ISSUE TITLE
Handling different resolution with same image name

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#198]
Currently, I see that if I take the screenshot of the same image in a different resolution and try to make a comparison, I get a alert that it cannot calculate difference.! (Attached screenshot)
![Screenshot (165)_LI](https://user-images.githubusercontent.com/50797731/106638713-2c7a7280-65aa-11eb-8a18-1b95fb1582b8.jpg)

Having a look at the definition from VRT Readme, **TestVariation - historical record of Baselines by Name + Branch + OS + Browser + Viewport + Device**, shouldn't the different resolution image be treated as a whole new image itself? In reference to above example : both the images irrespective of having the same name should be treated separately as their resolution is different. Correct me if I am missing on anything. @pashidlos

**Comment by pashidlos** [comment]
@priyankachaturvedi30 real size is the size of an image taken not the viewport 
from your screenshot I could see that you are not setting `viewport` for an image
add it in method for image upload in addition to `name` in track method (depending on integration lib you are using)

yes, you  are right, in case viewports are different images are treated as different

**Comment by pashidlos** [comment]
this is how it looks when viewport is provided
<img width="650" alt="1" src="https://user-images.githubusercontent.com/5182956/106743325-e6172900-6626-11eb-8d5d-f16aaefb3d43.png">

**Comment by priyankachaturvedi30** [comment]
Great ! Thanks @pashidlos Let me try this one out.
