### ISSUE TITLE
Create .Net SDK

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#20]
- [x] update README with new SDK and examples urls

**Comment by dcrowe** [comment]
I'll put my hand up for this.

**Comment by dcrowe** [comment]
Initial progress here https://github.com/dcrowe/sdk-dotnet/tree/initial-sdk

Outstanding tasks:
- [ ] CI
- [ ] config from file
- [ ] config from environment
- [ ] readme

**Comment by pashidlos** [comment]
@dcrowe awesome!
you are invited into `sdk-dotnet` team with all access to repos:
https://github.com/Visual-Regression-Tracker/sdk-dotnet
https://github.com/Visual-Regression-Tracker/examples-dotnet

**Comment by dcrowe** [comment]
Can you please create a nuget.org account, so I ca make you a package owner?

**Comment by dcrowe** [comment]
@pashidlos Do you mind setting up codacy for me?

**Comment by dcrowe** [comment]
Looks like I need to wait a day before net5.0 becomes supported by github: https://github.com/actions/virtual-environments/issues/1891

**Comment by pashidlos** [comment]
> @pashidlos Do you mind setting up codacy for me?

done

**Comment by dcrowe** [comment]
https://github.com/Visual-Regression-Tracker/sdk-dotnet/pull/4
https://github.com/Visual-Regression-Tracker/examples-dotnet/pull/2

**Comment by pashidlos** [comment]
@dcrowe it's gonna make huge impact on project!
thank you for support!
