### ISSUE TITLE
Providing access control corresponding to user profiles

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#201]
@pashidlos : Currently I see New users and projects could be created via the frontend app once the setup is up and running.
However, I am looking for something through which I can have access control specific to certain projects/users otherwise if multiple teams across projects are working simultaneously my data (baseline to be more particular) are visible and editable by all. Can I control it somehow?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 we have something similar to this already requested #144
for next major version I'll think of some kind of user permissions in order to achieve this

**Comment by priyankachaturvedi30** [comment]
Thanks @pashidlos . That would be great 👍

**Comment by priyankachaturvedi30** [comment]
Hey @pashidlos : any updates on when we would be rolling this out?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 not for now 😔
currently changes are planned in next major release 
you could follow updates in this ticket https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/144
