### ISSUE TITLE
Implement user friendly error messages in VRT

### ISSUE THREAD

**Issue by suratdas** [Visual-Regression-Tracker/Visual-Regression-Tracker#203]
In some cases, we have to change error messages to more user-friendly messages. For example, 

![image](https://user-images.githubusercontent.com/9042580/107295162-b18adf00-6a23-11eb-9210-24f380b4cdbf.png)

**Comment by suratdas** [comment]
I can take this ticket implementation if it's okay.

**Comment by pashidlos** [comment]
@suratdas thanks for the ticket!
it's on you!

**Comment by pashidlos** [comment]
@suratdas thanks for you contribution!
