### ISSUE TITLE
TestRun list. Cannot navigate to next when last on the page selected

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#207]
I recently upgraded from 4.8 to 4.9 and I see a few of the changes which have now been removed. 
1. Filter - That provided flexibilty to filter my screenshots, based on Status/Name etc. It was of great help when I had huge amount of screenshots in the single build. Should we not consider replacing that filter there?
2.  Introduction to pagination have restricted the usage for right arrow(Attached snippet) for navigation onto the next images once the images of one page have been completed.  If we can continue navigating to the images of next page that would be of help.
![image](https://user-images.githubusercontent.com/50797731/107772768-afe25380-6d62-11eb-82ab-8686dc89feaf.png)

**Comment by pashidlos** [comment]
@priyankachaturvedi30 thanks for noticing 
1. with pagination added filters gonna be reworked in scope of #194
2. good catch, will fix in scope of this ticket
