### ISSUE TITLE
Do we need a toggle when the images are matched ?

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#211]
Currently, the toggle is used to view the difference between the current image and the baseline image. 
![image](https://user-images.githubusercontent.com/50797731/108021125-e5798c00-7043-11eb-8c2b-1a99a38d6cbf.png)

In a scenario where there is no difference between the 2 images and the status of comparison is OK (Attached image), if I click the toggle then it shows "No Image Available". Can we disable the toggle such cases? Or can this be better handled?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 thanks for request
we could disable toggle in case there is no image

**Comment by priyankachaturvedi30** [comment]
Also, observed one small cosmetic issue (very low priority) in 4.10.0 release version.
![image](https://user-images.githubusercontent.com/50797731/108364023-971ee580-721b-11eb-8f76-80b3418d152b.png)

When there is Approve All button. the bottom of the line showing statistics kind of gets overlapped. Please add a little space or reduce the size of Approve all button to fix this :)

**Comment by pashidlos** [comment]
> Also, observed one small cosmetic issue (very low priority) in 4.10.0 release version.
> ![image](https://user-images.githubusercontent.com/50797731/108364023-971ee580-721b-11eb-8f76-80b3418d152b.png)
> 
> When there is Approve All button. the bottom of the line showing statistics kind of gets overlapped. Please add a little space or reduce the size of Approve all button to fix this :)

sure, thanks for noticing 
moved this into separate issue #216
