### ISSUE TITLE
TestRun list. Approve All button. the bottom of the line showing statistics kind of gets overlapped.

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#216]
Also, observed one small cosmetic issue (very low priority) in 4.10.0 release version.
![image](https://user-images.githubusercontent.com/50797731/108364023-971ee580-721b-11eb-8f76-80b3418d152b.png)

When there is Approve All button. the bottom of the line showing statistics kind of gets overlapped. Please add a little space or reduce the size of Approve all button to fix this :)

_Originally posted by @priyankachaturvedi30 in https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/211#issuecomment-781345804_

**Comment by suratdas** [comment]
Unable to reproduce with the latest code.
![image](https://user-images.githubusercontent.com/9042580/109208175-ddfe6500-775e-11eb-803f-8b72151e92ef.png)
@priyankachaturvedi30  Is there any specific browser or config I have to use to be able to reproduce?
