### ISSUE TITLE
Add example config for Kubernetes

### ISSUE THREAD

**Issue by alexandru-patrascu-mpf** [Visual-Regression-Tracker/Visual-Regression-Tracker#217]
### Please add support for Kubernetes deployment. 
Since Kubernetes is very commonly used, support for easy deployment of VRT ecosystem would be more then helpful. It would attract more users (due to both Docker and Kubernetes support) and it would increase the adoption in large scale enterprise environments, which tend to use K8s clusters.

Nice to have:

- deployment yaml file for **postgresql**
- deployment yaml file for Visual Regression Tracker **UI**
- eployment yaml file for Visual Regression Tracker **API**

**Comment by pashidlos** [comment]
@alexandru-patrascu-mpf thanks for your request!
have you tried converting `docker-compose` into helm chart?
https://kubernetes.io/docs/tasks/configure-pod-container/translate-compose-kubernetes/

**Comment by marcm-qa** [comment]
Maybe I can help a little bit.
I have a bunch of kubernettes manifest files (think they are called that) that sort of work....
This is working:
1. Postgres configured with storage
2. Migration works - can see that tables are created.
3. API configured with storage - this "works" as I can see the entry in the log file when I call the endpoint with a GET.

I am having issues with the UI. I can add the UI and get the login page. The login page does not work.

I am happy to post the files if somebody is willing to "fix" them and share?

**Comment by davidlinse** [comment]
any news on this ?

**Comment by Roemer** [comment]
I am running it in kubernetes (at least the api and ui). I can add those files on thursday,

**Comment by Tri0L** [comment]
I think I can help with helm chart creation if needed.

**Comment by pashidlos** [comment]
example config added on wiki 
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/wiki/Kubernetes-Configuration-Example

**Comment by monotek** [comment]
There is a visual-regression-tracker Helm chart available now too: 
https://github.com/kokuwaio/helm-charts/tree/main/charts/visual-regression-tracker
