### ISSUE TITLE
Semver & compatibility matrix

### ISSUE THREAD

**Issue by benquinteros** [Visual-Regression-Tracker/Visual-Regression-Tracker#220]
Is it fair to say the project is following semver? In regards to the various sdks/agents is a compatibility matrix needed?

**Comment by pashidlos** [comment]
@benquinteros yes, you are right 
using the same major version guaranties full compatibility 
difference in minor version could be some features added/modified 
patch version is about hot fixes

I'll make a WIKI page on this matter

**Comment by pashidlos** [comment]
Page with basic information is created, let me know if you think is not enough 
release notes for SDK versions is not always updated so we gonna automate this process #111
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/wiki/How-to-choose-right-SDK---agent-version
