### ISSUE TITLE
Variations : On deleting a variation, there is an error.

### ISSUE THREAD

**Issue by suratdas** [Visual-Regression-Tracker/Visual-Regression-Tracker#233]
Getting below error on trying to delete a test variation.

"Invalid `prisma.testVariation.delete()` invocation: The change you are trying to make would violate the required relation 'TestRunToTestVariation' between the `TestRun` and `TestVariation` models."

![image](https://user-images.githubusercontent.com/9042580/109348433-5fbac500-7829-11eb-8766-374d3a0190f9.png)

**Comment by pashidlos** [comment]
@suratdas thanks for noticing
gonna add e2e test for this case
