### ISSUE TITLE
Potential Bug: Time shown on Builds screen is not current time

### ISSUE THREAD

**Issue by marcm-qa** [Visual-Regression-Tracker/Visual-Regression-Tracker#238]
Not sure if this is a bug or as a result of my lack of knowledge / experience of Docker, but the time shown on the Builds screen is not in my local time.
A test was run at about 09:00 UK time and the time displayed on the ui is 5:46pm.

![image](https://user-images.githubusercontent.com/80327313/110766029-a9a1a300-824c-11eb-9d3e-bf3c93a90497.png)

**Comment by pashidlos** [comment]
@marcm-qa thanks for reaching out
time here is taken from server when record is put in DB 
could you check what timezone is set there?

**Comment by marcm-qa** [comment]
I hope this helps, I am a newbie t o postgres and Docker - I could not query the db via pgAdmin, so I exported the DB as SQL:

This is the create script:

CREATE TABLE public."Build" (
    id text NOT NULL,
    number integer,
    "branchName" text,
    status text,
    "projectId" text NOT NULL,
    "updatedAt" timestamp(3) without time zone NOT NULL,
    "createdAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "userId" text,
    "isRunning" boolean,
    "ciBuildId" text
);

and the data in the Build table:

--
-- TOC entry 2984 (class 0 OID 16409)
-- Dependencies: 204
-- Data for Name: Build; Type: TABLE DATA; Schema: public; Owner: postgres
--

```
COPY public."Build" (id, number, "branchName", status, "projectId", "updatedAt", "createdAt", "userId", "isRunning", "ciBuildId") FROM stdin;
97f1c73f-a600-4c29-9823-985b84518f72	44	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-10 14:50:00.192	2021-03-10 14:48:52.701	\N	f	637510133862363692
73ce20cb-628e-485c-a3a8-1cddcbd8e0ed	55	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-10 15:34:59.125	2021-03-10 15:32:31.262	\N	f	637510160045197979
9b2e45d0-b33d-4796-835e-7b742bca3ee5	1	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-09 17:06:14.862	2021-03-09 14:06:47.357	\N	f	commit_sha
acaae424-d6d3-4f5a-888f-d838fc89fc2f	4	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-09 18:41:55.076	2021-03-09 18:41:35.009	\N	f	637509120872620620
b18b9d76-2ae6-415d-97aa-35eefa14ae7f	3	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-09 18:42:48.907	2021-03-09 18:39:36.8	\N	f	637509119628109185
55c1ff2e-b417-430c-b1e1-c373fb1d1489	6	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-09 18:46:51.534	2021-03-09 18:46:51.033	\N	f	637509124107184991
3e4dafa6-405e-4aa1-8419-7776035d6d8f	5	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-09 18:46:58.023	2021-03-09 18:44:04.687	\N	f	637509122305782382
a786a6a7-627a-46ba-afd2-fc90e81ca3cb	56	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-10 15:45:25.247	2021-03-10 15:44:55.48	\N	f	637510167484592091
ca2cc395-780d-4d05-91be-5c12237808e7	7	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-09 18:49:35.229	2021-03-09 18:47:41.792	\N	f	637509124615081202
ecd44c8a-ed8d-4d61-bbc8-60832ead0d3e	9	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-09 18:49:44.142	2021-03-09 18:49:43.642	\N	f	637509125833588008
f47c4a4c-c293-4fa1-8d48-3b3b371a4f52	57	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-10 17:01:00.467	2021-03-10 17:00:49.625	\N	f	637510472556608931
7898ce82-f86f-4289-a445-d71e3e59ed09	58	develop	\N	f7f9cfd6-15ae-43b9-8e09-b34fb289c38c	2021-03-10 17:47:10.002	2021-03-10 17:46:56.518	\N	f	637510500213005814
```

**Comment by pashidlos** [comment]
@marcm-qa thanks for additional info 
I could see build `58` with createdAt `2021-03-10 17:47:10.002` it's in UTC
on frontend it get's converted to local date time so for UK it's the same

or it's not about timezone?
do you have some steps to reproduce it?

**Comment by marcm-qa** [comment]
Hi
All I did was to run the docker compose file which I got from this site.
I am using a Windows 10 machine,
I might get a chance to try it again this week.

**Comment by pashidlos** [comment]
@marcm-qa sure
let me know if it's still an issue

**Comment by marcm-qa** [comment]
I can not repro the issue, sorry about that.
