### ISSUE TITLE
Feature Request: Smart ignore area features

### ISSUE THREAD

**Issue by marcm-qa** [Visual-Regression-Tracker/Visual-Regression-Tracker#239]
First, I just want to say great software.

It would be nice to have the ability to add the same ignore area to multiple images e.g. 
I have a set of images of a sales order and each sales order has an order number.
I want to be able to add an ignore area to one of the images and then copy the same area to the other images.

As an extension:
Have VRT recognise previously ignored areas and suggest to add them, e.g. the flashing carat in input boxes :-)

**Comment by pashidlos** [comment]
@marcm-qa thanks for your request
I would not recommend to use this approach on multiple images as for me it's more workaround than actual fix 

> I have a set of images of a sales order and each sales order has an order number.
you could add ignore areas while image uploading
it's supported in every integration library so you just need to find the way how to get coordinates for it

> the flashing carat in input boxes
that will be possible to overcome using another comparison library added in scope of #219
