### ISSUE TITLE
Irrespective of Branch name, if project names matches - vrt processes the image

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#241]
Potential bug introduced in 4.11 release.

Suppose I have the below configuration setup in my vrt- 
![image](https://user-images.githubusercontent.com/50797731/110936177-7c411c00-8356-11eb-8abe-fb625434762a.png)
Now, if instead of branch name - testbrach if i pass any random value it still processes the comparison/screenshot under my specified project (Default project in this case). This was not a issue in previous release where it use to through the message that branchname not found (something of similar sort) . Can you please double check once.

**Comment by pashidlos** [comment]
@priyankachaturvedi30 thanks for your request 
there is validation for project name but not for branch name
it's possible to use any branch name for tracking and they are treated as feature branches 
the difference between main and feature branch is that in case there is no baseline for feature branch 
it'll try to compare it with main one
