### ISSUE TITLE
Baselines are not created when there are multiple per test

### ISSUE THREAD

**Issue by marcm-qa** [Visual-Regression-Tracker/Visual-Regression-Tracker#253]
Using version 4.12.0
Docker
Windows 10
New system or adding baselines

If I have 3 tests with 1 visual check each , then I see 3 checks in the test run results

If I have 1 test with 3 visual checks (each has a unique name) then I see only 1 check in the run results.
If I approve the baseline, and re-run the tests, I then see the approved baseline and a new result.

**Comment by marcm-qa** [comment]
Oops I think i just figured why this is happening :-)
Not sure if it is a bug or by default, or if i need to set a flag.

So in the situation of 1 test, 3 checkpoints, the first time you run the test the baseline does not exist and the test fails, therefore the subsequent checks are not performed.

**Comment by pashidlos** [comment]
@marcm-qa in case when test contains several new baselines 
it make sense to enable `enableSoftAssert` option in agent configuration not to fail the test
and then switch it off

should I close the ticket?

**Comment by marcm-qa** [comment]
you can close it :-)
Thanks
