### ISSUE TITLE
Cypress-agent. No Response from Server when sending larger Images (> 7mb)

### ISSUE THREAD

**Issue by dekaravanhoc** [Visual-Regression-Tracker/Visual-Regression-Tracker#254]
What did I do?
Tracked a relativ long page in 1920p

What did I expect?
Tracked page is transferred to the server and added to the project

What happend?
 CypressError: `cy.task('VRT_TRACK_IMAGE')` failed with the following error:
> No response from server

Additional Info:
Parser Limit is set to 200mb
Cypress_Agent was used
Probably Images above 7mb are problematic (did some tests here with different sizes)

**Comment by dekaravanhoc** [comment]
> @dekaravanhoc thanks for your request
> could you provide logs from `docker-compose` if there any errors?

{
  "response": {
    "statusCode": 401,
    "message": "Unauthorized"
  },
  "status": 401,
  "message": "Unauthorized"
}
 +227950692ms
Error: Unauthorized
    at JwtAuthGuard.handleRequest (/node_modules/@nestjs/passport/dist/auth.guard.js:64:30)
    at /node_modules/@nestjs/passport/dist/auth.guard.js:48:128
    at /node_modules/@nestjs/passport/dist/auth.guard.js:82:24
    at allFailed (/node_modules/passport/lib/middleware/authenticate.js:107:18)
    at attempt (/node_modules/passport/lib/middleware/authenticate.js:180:28)
    at JwtStrategy.strategy.fail (/node_modules/passport/lib/middleware/authenticate.js:302:9)
    at /node_modules/passport-jwt/lib/strategy.js:106:33
    at /node_modules/jsonwebtoken/verify.js:152:16
    at getSecret (/node_modules/jsonwebtoken/verify.js:90:14)
    at Object.module.exports [as verify] (/node_modules/jsonwebtoken/verify.js:94:10)

**Comment by pashidlos** [comment]
@dekaravanhoc any other errors?
this one related to failed authorisation

**Comment by pashidlos** [comment]
@dekaravanhoc could you also check if cypress is actually taking the screenshot?
check if image file is created
```
cy.screenshot("some name")
```

**Comment by pashidlos** [comment]
this one is similar to https://github.com/Visual-Regression-Tracker/agent-cypress/issues/75

**Comment by dekaravanhoc** [comment]
> @dekaravanhoc any other errors?
> this one related to failed authorisation

No thats the only one. This also should be the one in connection with the failed attemp. Maybe there is a timing issue regarding the authentication - to long for the upload. As with Images around 7mb it sometimes works and sometimes not. 

> @dekaravanhoc could you also check if cypress is actually taking the screenshot?
> check if image file is created
> 
> ```
> cy.screenshot("some name")
> ```

Yes. I did that. Also it runs through multiple pages in one testrun, where only the last page is not uploaded. All the others work fine.

> this one is similar to [Visual-Regression-Tracker/agent-cypress#75](https://github.com/Visual-Regression-Tracker/agent-cypress/issues/75)

Ah ok. I was already searching for the problem and did not found it. Seemed weird though, that no one else had the problem.

**Comment by pashidlos** [comment]
@dekaravanhoc let me know if increase in timeout helps 
not sure if you could increase it globally for all cypress screenshot commands

**Comment by dekaravanhoc** [comment]
@pashidlos 
The sceenshot for the page is taken without problems.
Also the track command works with clipping the width of the shot, till its size gets smaller then 7mb (or around 7mb). (Using the clip option.)

**Comment by pashidlos** [comment]
@dekaravanhoc could you reproduce the issue using example project?
I'll need some reproducible steps to debug what is happening 
https://github.com/Visual-Regression-Tracker/examples-js/tree/master/agent-cypress

**Comment by dekaravanhoc** [comment]
@pashidlos Here is the Example: https://github.com/dekaravanhoc/examples-js/tree/master/agent-cypress
Run vrt.spec - the last image will produce the error. At least here.
screenshot.spec just takes screenshots of the same setup, do see weither everything is working on that side.

**Comment by pashidlos** [comment]
@dekaravanhoc I'm still on that issues 
was able to reproduce thanks to your example 
seems cypress is failing to encode such image into base64
I guess it might be solved https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/247
let me check

**Comment by pashidlos** [comment]
@dekaravanhoc could you try new version with multipart upload version `5.0.0`?
https://github.com/Visual-Regression-Tracker/agent-cypress/releases/tag/v5.0.0
