### ISSUE TITLE
[Improvement] Reduce the white space between screenshots in the screen difference screen

### ISSUE THREAD

**Issue by mseremin** [Visual-Regression-Tracker/Visual-Regression-Tracker#259]
It would be great to put screenshots close together when approving / rejecting a result. 
This will make the result more readable for testers / developers.
<img width="577" alt="image" src="https://user-images.githubusercontent.com/45852826/116217948-b887da80-a752-11eb-8879-83853255c084.png">

**Comment by pashidlos** [comment]
@mseremin thanks for request
default behaviour is to fit whole image into screen to see areas with diffs at once and then zoom to needed area
fitting image by width would require to scroll if image height is grater  
you could change zoom via mouse wheel as well as switch to original size using control buttons  
![1](https://user-images.githubusercontent.com/5182956/116253877-8c338480-a779-11eb-8ae2-6d96bb7446e5.png)

**Comment by mseremin** [comment]
@pashidlos Thanks for the quick response !
