### ISSUE TITLE
[Feature] Filter operator "not-equals" for "status" and fast-filter button on ui

### ISSUE THREAD

**Issue by frezot** [Visual-Regression-Tracker/Visual-Regression-Tracker#261]
1. It will be useful to have possibility make filter `status !== ok`

2. Will be great if tag `unresolved` on testrun works as button for fast apply this filter

<img width="1352" alt="Screenshot 2021-04-27 at 16 26 40" src="https://user-images.githubusercontent.com/7229738/116219761-2b567d00-a776-11eb-8bb7-2e0fbf09fee8.png">

**Comment by pashidlos** [comment]
> 1. It will be useful to have possibility make filter `status !== ok`

could you elaborate what is the use case?
we could add some custom filters there https://material-ui.com/ru/components/data-grid/filtering/#custom-filter-operator

> Will be great if tag unresolved on testrun works as button for fast apply this filter

not sure that this would be useful as build status is changing all the time
would default sorting by `unresolved` status solve the issue?
