### ISSUE TITLE
Can upload non PNG images

### ISSUE THREAD

**Issue by suratdas** [Visual-Regression-Tracker/Visual-Regression-Tracker#262]
How should non-png images behave? Currently, VRT takes such an image (e.g. jpg image) but when I try to approve, it throws an error. Reject works, however.
![image](https://user-images.githubusercontent.com/9042580/116581950-b8f6b180-a8c9-11eb-903f-314166dc807a.png)

**Comment by pashidlos** [comment]
@suratdas thanks for your request
could you clarify how you sent non PNG image to service?
could you share stacktrace?

**Comment by suratdas** [comment]
I used the [Java standalone example](https://github.com/Visual-Regression-Tracker/examples-java/tree/master/standalone-from-folder-maven) to push a jpg file. I am not sure which stack trace you are referring to here.

**Comment by pashidlos** [comment]
@suratdas any client or backend error?
to see where is the code fails

**Comment by suratdas** [comment]
Below is the backend error when trying to approve a jpg image.

[Nest] 3870   - 05/10/2021, 6:53:53 PM   [TestRunsService] Approving testRun: fad719c3-9046-46e1-8349-d3b2a8179ca2 merge: false autoApprove: false
[Nest] 3870   - 05/10/2021, 6:53:53 PM   [StaticService] Cannot get image: 1620694072700.screenshot.png. Error: Invalid file signature +23ms
[Nest] 3870   - 05/10/2021, 6:53:53 PM   Object:
{}
 +2ms
TypeError: Cannot read property 'width' of undefined
    at module.exports (/Users/surat/vrt-backend/node_modules/pngjs/lib/packer-sync.js:28:40)
    at Object.exports.write (/Users/surat/vrt-backend/node_modules/pngjs/lib/png-sync.js:11:10)
    at TestRunsService.approve (/Users/surat/vrt-backend/dist/src/test-runs/test-runs.service.js:73:88)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Let me know how to proceed
- Block processing of non-png at the SDK level.
- Add logic to process jpg image types in VRT backend.
- Leave it as it is and update documentation.
