### ISSUE TITLE
screenshots of angular js .window-dialog on Firefox do not work 

### ISSUE THREAD

**Issue by AlexBalakersky** [Visual-Regression-Tracker/Visual-Regression-Tracker#264]
cy.get('.window-dialog').vrtTrack("Edit connection dialog", {diffTollerancePercent: 1})

this takes screenshot of the area 'underneath' the dialog on FF (Chrome and Edge work as expected)

**Comment by AlexBalakersky** [comment]
"dependencies": {
    "@visual-regression-tracker/agent-cypress": "^4.8.0",
    "basic-authorization-header": "^0.2.7",
    "cypress-plugin-snapshots": "^1.4.4"
  }

**Comment by pashidlos** [comment]
@AlexBalakersky thanks for request 
could you check how the pure `cy.screenshot` method works?
need to make sure that the images taken are the same that send to VRT

**Comment by AlexBalakersky** [comment]
Hi, thanks for quick response.
I've checked and the problem is in cy.screenshot
it sends incorrect image
will open an issue for Cypress.
