### ISSUE TITLE
Updating postgres password from .env file

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#271]
Just checking on the possibility to update the postgress password through env files, since it is too weak and vulnerable for attacks.
Can changing it have impact on existing baselines/run history/data etc ?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 thanks for your request
sure, you are free to change it in `.env` file

also it's possible ti change password for already create container as described in this answer
https://stackoverflow.com/questions/58643652/how-to-change-postgresql-docker-image-password
