### ISSUE TITLE
Python - Playwright.  Firefox browser seems not to be working with python playwright integration

### ISSUE THREAD

**Issue by killroy333** [Visual-Regression-Tracker/Visual-Regression-Tracker#273]
What did I do?
Launched  Python + SDK example from link below with` browserType` set to `playwright.firefox`
https://github.com/Visual-Regression-Tracker/examples-python/tree/master/playwright

What did I expect?
The process is completed without problems and result appears in VRT server.

What happend?

`Process finished with exit code 1`, with "`playwright._impl._api_types.Error: Not implemented`" Error
 ![failedtest](https://user-images.githubusercontent.com/66221743/120462247-69614500-c3a3-11eb-9aeb-5be509e04e92.png)

**Comment by pashidlos** [comment]
@killroy333 seems to be `playwright` issues 
FF is not able to take screenshot with `omit_background` option
```python
        page.screenshot(omit_background=True)
```
