### ISSUE TITLE
Enable to bulk clear ignore area for test runs list and details view

### ISSUE THREAD

**Issue by suratdas** [Visual-Regression-Tracker/Visual-Regression-Tracker#276]
Let's consider following conditions
1. I want to verify mobile images where I want to ignore the header (contains dynamic value like network strength, battery level, time etc.)
2. I have animation in all images in a particular area
3. I have header/footer in all images which have different theme/logo/font and I want to ignore them from my visual comparison.

Manually applying ignore area for all images is troublesome especially if we have a lot of images in the build. There should be some mechanism to apply ignore all for all images. Similarly, if I want to clear/modify ignore areas for all, there must be some way to achieve that.

**Comment by suratdas** [comment]
Something like this image

![image](https://user-images.githubusercontent.com/9042580/122467604-9438c500-cf6f-11eb-897f-6597405966ea.png)

**Comment by pashidlos** [comment]
@suratdas the idea of having some bulk operations helping to manage results on UI side sounds really appealing to me 
I would suggest to separate it onto smaller parts something like 
- clear ignore area
- copy ignore area from one to another
- bulk operation with those

meanwhile have you tried to add ignore areas programmatically via SDK?
this might help to accomplish something similar while this is not yet implemented

**Comment by pashidlos** [comment]
@suratdas thanks for contribution!
