### ISSUE TITLE
Implement frontend help/guide in the UI

### ISSUE THREAD

**Issue by suratdas** [Visual-Regression-Tracker/Visual-Regression-Tracker#280]
A help page in any of the following form will be helpful for easier understanding of features across various pages in VRT.
1. https://react-joyride.com/ 
2. Help web page in VRT
3. Dedicated website for VRT help

**Comment by pashidlos** [comment]
@suratdas that is awesome idea 
would you like to try it?

**Comment by suratdas** [comment]
I will work on it. Will implement option 1, react-joyride.

**Comment by pashidlos** [comment]
@suratdas thanks for contribution!
