### ISSUE TITLE
Same API key works for all irrespective of user account

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#282]
I see that the default user created with - visual-regression-tracker@example.com, which has its own specific API key.
I created yet another user using Create Account - and for that user, it created a new API Key. 
![image](https://user-images.githubusercontent.com/50797731/124438561-f67a2e00-dd95-11eb-994c-0ed7e943f8b4.png)

However, I am still able to use any of the 2 API key's that I have and access execution results created on the portal using any of the keys. What is the purpose of associating the new API key with new user created when there is no access control mechanism? @pashidlos : Can you point out something that I am missing here.?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 thanks for request 
you are right, currently there is no logic regarding access restriction 
later this gonna be used to restrict accesses within projects/users as well as history of user actions
