### ISSUE TITLE
Source Code href broken in readme

### ISSUE THREAD

**Issue by vivekbwaj** [Visual-Regression-Tracker/Visual-Regression-Tracker#283]
On url https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/wiki/Storybook
At the bottom of the page
![image](https://user-images.githubusercontent.com/20886136/124676904-c13f1e80-df02-11eb-975e-61353d83750d.png)

![image](https://user-images.githubusercontent.com/20886136/124677001-f2b7ea00-df02-11eb-876d-03eca8c5ea83.png)

**Comment by pashidlos** [comment]
@vivekbwaj thanks for request
link is fixed now
https://github.com/Visual-Regression-Tracker/examples-js/tree/master/storybook
