### ISSUE TITLE
Variable reference from .env file - BODY_PARSER_JSON_LIMIT

### ISSUE THREAD

**Issue by priyankachaturvedi30** [Visual-Regression-Tracker/Visual-Regression-Tracker#284]
@pashidlos : I was trying out few config related settings where I encountered a property in .env file by the name - BODY_PARSER_JSON_LIMIT. Can you explain to me what does it define ?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 that config could restrict upload images bigger than this limit
