### ISSUE TITLE
Can we have a .dotnet example of using Custom Tags

### ISSUE THREAD

**Issue by marcm-qa** [Visual-Regression-Tracker/Visual-Regression-Tracker#295]
Hi
I am using VRT on a dotnet core application ("VisualRegressionTracker" Version="4.7.0"). We want to add "Language" as an option to the Track() method, as you can for OS, Device, Browser etc.

I see that custom tags can be added (https://github.com/Visual-Regression-Tracker/backend/pull/136/) but cannot figure out how to do it in dot net.

Any help would be appreciated

**Comment by pashidlos** [comment]
@marcm-qa thanks for your request 
at this point custom tag is not implemented in .Net SDK https://github.com/Visual-Regression-Tracker/sdk-dotnet

if I'm not mistaken it's generating http client based on swagger docs 
https://github.com/Visual-Regression-Tracker/sdk-dotnet/blob/main/VisualRegressionTracker/Api.json

would you like to contribute?

**Comment by marcm-qa** [comment]
Hi, I can try to implement custom tags in .net SDK, no sure where to start as custom tags are not in the swagger definition we are using 4.14.0.

**Comment by marcm-qa** [comment]
Quick update, I have got the latest version 4.17.0 and I see the custom tags in the swagger, so I now know where to start.
Lets see what I can do :-)

**Comment by pashidlos** [comment]
@marcm-qa let me know if there are any incompatibility and swagger json could not be parsed correctly

**Comment by marcm-qa** [comment]
Hi. I have some changes to push in a new but I am getting a 403 when trying to push to 'https://github.com/Visual-Regression-Tracker/sdk-dotnet.git/.
I have upped the nuget version to 4.7.1, updated the unit test
Verified the change actually works :-)
Just stuck on permissions.
Any help would be appreciated.

Thanks

**Comment by pashidlos** [comment]
@marcm-qa invited you to .net SDK team 
accept it and try to create PR

**Comment by pashidlos** [comment]
@marcm-qa thanks for contribution 

released in version 4.7.1
https://www.nuget.org/packages/VisualRegressionTracker/4.7.1
