### ISSUE TITLE
Manual Merge from Pr-200 to master don't work and i got 500. error

### ISSUE THREAD

**Issue by austimchik** [Visual-Regression-Tracker/Visual-Regression-Tracker#298]
If we have only new screenshots in the branch, then when we try to merge the branch in the mater, we will get a 500 error.

```
"Cannot read property 'branchName' of undefined"
name: "TypeError"
path: "/test-variations/merge?projectId=3424234&fromBranch=PR-200&toBranch=master"
stack: "TypeError: Cannot read property 'branchName' of undefined\n    at TestVariationsService.merge (/dist/test-variations/test-variations.service.js:140:51)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

**Comment by pashidlos** [comment]
@austimchik thanks for request

I was't able to reproduce the issue 
in case source branch has no baselines I get empty build so it works as expected 

could you specify steps to reproduce?

**Comment by austimchik** [comment]
Sorry that I didn't answer for a long time, now it has stopped playing. There may have been glitches after the big update.
