### ISSUE TITLE
Can't see status response from VRT server

### ISSUE THREAD

**Issue by tsboris** [Visual-Regression-Tracker/Visual-Regression-Tracker#301]
Hi,

I need assistance in getting the status response from the VRT server.
I've a setup a cypress test using Jenkins pipelines and have successfully integrated the VRT server with Cypress.

When Jenkins runs the Cypress tests, screenshots are getting through to VRT server.Project, branch and build id are also working properly and a I can see them in the VRT UI.

In some of your screenshots I saw that you are checking/looking for a string that starts with "VRT status ..."

What I can't understand is how to get VRT status to display in the Jenkins console and also, how to generate the VRT HTML report.

The entire setup is in nodes.js and typescript.

Is there a definition I'm missing?

Thanks,
Boris.

**Comment by pashidlos** [comment]
@tsboris thanks for your request 

> In some of your screenshots I saw that you are checking/looking for a string that starts with "VRT status ..."

could you elaborate on that?

> What I can't understand is how to get VRT status to display in the Jenkins console and also, how to generate the VRT HTML report.

there is no specific VRT status as all the tests are the part of Cypress tests
you should be able to generate HTML report the same as you do for regular Cypress tests
if the idea is to have list of tests in Jenkins there should be a teamcity plugin for Cypress tests (something like https://medium.com/egnyte-engineering/3-steps-to-awesome-test-reports-with-cypress-f4fe915bc246)

**Comment by tsboris** [comment]
Hi Pavel,

Thank you for the quick response :-) 

> > _In some of your screenshots I saw that you are checking/looking for a string that starts with "VRT status ..."_
> 
> **could you elaborate on that?**

All screenshots under this path:
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/tree/master/public/jenkins_integration

> there is no specific VRT status as all the tests are the part of Cypress tests
> you should be able to generate HTML report the same as you do for regular Cypress tests
> if the idea is to have list of tests in Jenkins there should be a teamcity plugin for Cypress tests (something like https://medium.com/egnyte-engineering/3-steps-to-awesome-test-reports-with-cypress-f4fe915bc246)
> 

I do have an HTML report generated for Cypress tests.
Are you saying that if VRT is failed for a certain screenshot in a certain Cypress test, this will fail the Cypress test?
And that I should see failed VRT status in the Cypress HTML report?

Thanks!

**Comment by pashidlos** [comment]
Screenshots related to this 
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/wiki/How-to-publish-VRT-result-in-jenkins

> Are you saying that if VRT is failed for a certain screenshot in a certain Cypress test, this will fail the Cypress test?
And that I should see failed VRT status in the Cypress HTML report?

Yes, it should

**Comment by tsboris** [comment]
Great!
I'll give it a test.

Thanks :-)
