### ISSUE TITLE
SDK-Dotnet: Unexpected Status when AUTO_APPROVE_BASED_ON_HISTORY: "true"

### ISSUE THREAD

**Issue by marcm-qa** [Visual-Regression-Tracker/Visual-Regression-Tracker#308]
SDK-Dotnet VisualRegressionTracker v 4.7.1

The following error is generated when VRT is creating a baseline:
 System.AggregateException : One or more errors occurred. (Unexpected status)
  ----> VisualRegressionTracker.VisualRegressionTrackerError : Unexpected status

I think the fix is to update:
`    public enum TestRunStatus
    {
        New,
        Ok,
        Unresolved,
    }`

To match frontend/src/types/testStatus.ts:
`  
export enum TestStatus {
  new = "new",
  unresolved = "unresolved",
  failed = "failed",
  approved = "approved",
  autoApproved = "autoApproved",
  ok = "ok",
}`

I am happy to add the following to the TestRunStatus enum if needed:
Failed
Approved
AutoApproved

**Comment by pashidlos** [comment]
released in version `4.7.2` 

@marcm-qa thanks for contribution!
