### ISSUE TITLE
Exception when using manual merge (Variations screen)

### ISSUE THREAD

**Issue by Roemer** [Visual-Regression-Tracker/Visual-Regression-Tracker#326]
When doing a manual merge from branch-a to branch-b, I get a warning:
`Cannot read property 'branchName' of undefined`

**Comment by frezot** [comment]
Steps:
- Run local vrt on
- Create new project `REPRO`, select `master` as main branch
- Create any test, which has at leat 1 image
- Run test with config 
```js
    {
      apiUrl: "http://localhost:4200",
      apiKey: "....",
      project: "REPRO",
      branchName:  "dev",
      ciBuildId: `LocalRun_0`,
      enableSoftAssert: true,
    }
```
- Approve image using web-UI
- Go to project variations
- Merge dev->master
![image](https://user-images.githubusercontent.com/7229738/153838055-b60439af-aa8e-40f6-8351-6860eb4c50fc.png)


**Actual:**
```
"TypeError: Cannot read property 'branchName' of undefined
at TestVariationsService.merge (/dist/test-variations/test-variations.service.js:140:51)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```

**Expected:**
new testrun on master with approved baselines
