### ISSUE TITLE
[Feature request] Add to UI main page info about version VRT, DB and other

### ISSUE THREAD

**Issue by AndreyMelnichenko** [Visual-Regression-Tracker/Visual-Regression-Tracker#335]
Hi,
at first big thanks for VRT!!!
It would be grade to have info alert button with info about service as VRT version, DB version, user count, build count, test count...
 It could be located as example at main page or login page with

**Comment by pashidlos** [comment]
@AndreyMelnichenko thanks for request 
it's already developed gonna be available in `4.20.0` https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/323
