### ISSUE TITLE
PORT environment variable unused

### ISSUE THREAD

**Issue by bengy** [Visual-Regression-Tracker/Visual-Regression-Tracker#338]
Hello, I am currently trying out the visual-regression-tracker.
As the docker-compose example uses the PORT environment variable,
I thought it might use this port as the nginx default port.

Looking at the Docker file and the nginx/default.conf file I can see only port 8080 is used.
Consider removing the variable from the example or preferrably consider listening on the port specified in the environment variable
(To allow for dynamic port allocations without port mapping).
Looks like a good first issue to me if, interested I can create a pull request.

**Comment by pashidlos** [comment]
@bengy thanks for your request

sure, feel free to create PR with changes
