### ISSUE TITLE
Deployment docs and/or assistance

### ISSUE THREAD

**Issue by tubbo** [Visual-Regression-Tracker/Visual-Regression-Tracker#340]
As far as I can tell, there's no documentation surrounding how to actually deploy this server outside of an evaluation phase. This would make what I'm currently doing (attempting to deploy the API and UI to Cloud Run) a lot easier.

So far I've been winging it by using the script and then uploading Docker images to my Google Container Registry, which I can then deploy to Cloud Run. This worked in the past, but recently I've been getting this frustrating error in my deployed API instance:

```
2021-12-08 18:21:10.818 EST(node:13) UnhandledPromiseRejectionWarning: Error: Query engine exited with code 255
2021-12-08 18:21:10.818 EST
2021-12-08 18:21:10.818 EST at ChildProcess.<anonymous> (/node_modules/@prisma/client/runtime/index.js:27551:23)
2021-12-08 18:21:10.818 EST at ChildProcess.emit (events.js:315:20)
2021-12-08 18:21:10.818 EST at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

This doesn't happen when I run the `./vrt-install.sh` script or whatever locally, so I'm assuming it has something to do with my configuration. But without any guide whatsoever on how one might deploy this in the real world, I can't tell what I did wrong.

Other potentially relevant config (but how would I know that? these settings aren't documented anywhere!)

![Screen Shot 2021-12-08 at 6 28 31 PM](https://user-images.githubusercontent.com/113026/145307443-60e0da32-3c32-4a7b-b392-c55a8b201590.png)

I'd love to be able to use this, but I'm just not sure how.

**Comment by pashidlos** [comment]
@tubbo thanks for the request 
minimum required configuration for remote machine is to update URLs
you could find video of how to set up VRT via ssh https://www.youtube.com/watch?v=cPsHeKnqL2M

sorry, can't say anything looking on that error :(
make sure you are using latest container versions
