### ISSUE TITLE
Download images function not function as expected intermediately

### ISSUE THREAD

**Issue by blockchain-nz** [Visual-Regression-Tracker/Visual-Regression-Tracker#346]
**Issue detail:**
Select multiple images and click the download image button.
Intermediately, some files missing from the generated zip file, sometimes the zip file was not generated at all. If the images were downloaded once previously, it looks like they are cached, and the zip file was generated already while the image was downloading.

**Version**
Get the latest docker-compose.yml and .env, upgrade my environment from 4.20.0 to 4.20.1. 
Docker images as below:
    visualregressiontracker/ui:4.20.1
    visualregressiontracker/api:4.20.0
    postgres:12

**Enviroment**
Redhat as the server side
Chrome on windows as frontend side.

**Comment by suratdas** [comment]
Will be available in the next release.
