### ISSUE TITLE
Error response from daemon: manifest for visualregressiontracker/ui:4.20.3 not found

### ISSUE THREAD

**Issue by pakhilov** [Visual-Regression-Tracker/Visual-Regression-Tracker#350]
STR:
platform Mac OS  Monterey 12.3 Docker desktop 4.6.0 Node 14.17.2

curl https://raw.githubusercontent.com/Visual-Regression-Tracker/Visual-Regression-Tracker/master/vrt-install.sh -o vrt-install.sh
chmod a+x vrt-install.sh
Run the installation script
./vrt-install.sh

And have this error message:
rror response from daemon: manifest for visualregressiontracker/ui:4.20.3 not found: manifest unknown: manifest unknown

**Comment by pakhilov** [comment]
looks similar with this issue: https://wesley.sh/docker-error-response-from-daemon-manifest-not-found-manifest-unknown/

**Comment by pashidlos** [comment]
fixed
