### ISSUE TITLE
Changing days to cache, or amount to cache, doesnt clear old builds

### ISSUE THREAD

**Issue by azz0r** [Visual-Regression-Tracker/Visual-Regression-Tracker#353]
As above, if I updated a project I expect it to then clear out old builds.

Currently I have to manually clear old builds when disk space becomes an issue.

Cheers

**Comment by pashidlos** [comment]
@azz0r there are two mechanisms currently 
- before creating new build every time the count is checked if it exceeds than old one is removed
- old test variations are cleared every midnight  
- 
could you double check and specify what exactly is not working with steps?

**Comment by azz0r** [comment]
Hey thanks for the response, it works as you mentioned, had thought maybe updating the cache amount would trigger.

Thanks
