### ISSUE TITLE
No Baseline found 

### ISSUE THREAD

**Issue by ajaykumarrc** [Visual-Regression-Tracker/Visual-Regression-Tracker#359]
Have installed VRT with elasticsearch.  and using storybook example **https://github.com/Visual-Regression-Tracker/examples-js/tree/master/storybook**  with the below properties

const config = {
  apiUrl: "http://[IP]:30004",
  apiKey: "4Z0KD1TN4EM88TNQGHNX289ZHSH8",
  branchName: "Develop",
  project: "Test-123",
  enableSoftAssert: true,
  ciBuildId: new Date().getTime().toString(36),
};
![MicrosoftTeams-image](https://user-images.githubusercontent.com/103586435/168614575-a08deeef-18de-4fe2-adc7-5d6f5c52bd7c.png)

console.error
No baseline: http://[ip]:8000/9b3a3325-911e-4f3c-a6a0-7af703f4b905?buildId=2dce3fb6-7f3f-40b1-9cea-38d77d857096&testId=d733ff69-6e13-4e77-87e7-f164ed9da2de

**Comment by suratdas** [comment]
For the first time run, there will be no baseline. If you approve this run, it will become the baseline for the next run.
