### ISSUE TITLE
[Feature Request] Health, Liveness and Readiness Endpoints 

### ISSUE THREAD

**Issue by dimitriharding** [Visual-Regression-Tracker/Visual-Regression-Tracker#362]
When using VRT in a Kubernetes setup, it would be helpful to have a `/liveness` and `/readiness` since endpoints like these are needed to know when to restart containers.

Also, including a default `/health` endpoint would be suitable as well, this could take into consideration if the database connection is live also. 

Since the backend is using Nest, this can be added by using [@nestjs/terminus](https://docs.nestjs.com/recipes/terminus)

----
In my current Kubernetes setup, I am using the `/api` documentation endpoint for readiness and liveness checks, while it works, I don't believe it is ideal.

**Comment by pashidlos** [comment]
implemented by @bmbferreira
released in `api-v4.20.2`
