### ISSUE TITLE
Backup of images In VRT

### ISSUE THREAD

**Issue by dikshithasuvarna** [Visual-Regression-Tracker/Visual-Regression-Tracker#381]
@pashidlos,
Can you help us know if there is a way to store the VRT images on GitHub or take the backup of the images from VRT, as there has been instances where the baseline images have been deleted from the branch.

**Comment by nitschSB** [comment]
hi, I think you loose your baseline due to #382 . you may increase maxBranchLifetime for each project to avoid deletion until the bug is fixed.

**Comment by pashidlos** [comment]
main branch baseline images are stored regardless of time frame
only branch baselines are being deleted as obsolete
create new issue in case it's not the case
