### ISSUE TITLE
Before method giving "project not found" error I can't find any solution.

### ISSUE THREAD

**Issue by slymn00** [Visual-Regression-Tracker/Visual-Regression-Tracker#393]
`describe('example to-do app', () => {

    before(() => {
        cy.vrtStart();
        cy.viewport(1280, 720)
        cy.visit('https://www.enuygun.com/otel/')
    });

    after(() =>{
        cy.vrtStop();
    });

    it('send keys auto complete', () => {
        cy.get('[data-testid="header-logo"]').vrtTrack("header-logo-control")
        cy.get('[class="PhoneNumber"]').vrtTrack("call-center-control")
        let rand=generateRandom(15);
        let rand2=rand+generateRandom(7);
        cy.get('[data-testid=autocomplete-form-box]').click()
        cy.get('[data-testid="autocomplete-input"]').type('asdasd')
        cy.get('#react-autowhatever-1-section-0-item-0 > .sc-jRQBWg').click()
        cy.get('[data-testid="datepicker-form-box"]').click()
        cy.get('[data-testid=datepicker-day-valid]').eq(rand).click()
        cy.get('[data-testid=datepicker-day-valid]').eq(rand2).click()
        cy.wait(1000)
        cy.get('[data-testid="guest-form-box"]').click()
        cy.get('[data-testid=adult-remove-button]').click()
        selectAdultCount('[data-testid=adult-add-button]',2)
        selectChildCount('[data-testid=child-add-button]','4')
        cy.get('[data-testid="guest-form-submit"]').click()
        cy.get('[data-testid="search-form-button"]').click()
        cy.wait(4000)
        cy.get('#hotelList > :nth-child(2) > .mb-3').vrtTrack("axess control")       

    });

})`

This my code block but giving this error please someone help me guys.
Error
Project not found
Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: example to-do app

Cypress version: 12.6.0
VRT version: last update

@pashidlos 
<img width="438" alt="Screenshot 2023-02-19 at 14 50 34" src="https://user-images.githubusercontent.com/87445114/219946079-4b6591fe-95d7-4f60-ada2-43034e728a11.png">

**Comment by pashidlos** [comment]
@slymn00 thanks for the request 
could you check configuration ? https://github.com/Visual-Regression-Tracker/agent-cypress#configuration
make sure you created project in VRT and put correct project name/id in config

**Comment by slymn00** [comment]
> @slymn00 thanks for the request 
> could you check configuration ? https://github.com/Visual-Regression-Tracker/agent-cypress#configuration
> make sure you created project in VRT and put correct project name/id in config

Ohh, thanks a lot @pashidlos . My project name was wrong that's my big fault because I'm new in the cypress and vrt. 🙏
