### ISSUE TITLE
Frontend. Migrate to Playwright from Cypress

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#403]

**Comment by paazmaya** [comment]
How about having both Cypress and Playwright tests there, to showcase and make sure that both of the agents are working?

**Comment by pashidlos** [comment]
@paazmaya the current problem with Cypress is that version 9 is used that is quite outdated and we faced an issue running those tests on CI
those tests are checking frontend but not agents so don't think it's worth having both inside frontend repo
it's true that we are missing contracts and e2e tests for the rest of them

can't think of how to implement contract testing 
however we could add e2e tests inside each agent repo as there is VRT instance working publicly that could handle theirs requests
what do you think?

**Comment by paazmaya** [comment]
Definitely need the publicly running instance where to push the test images, for show case and for our internal testing, but somehow need to make it readable without login.

For the older versions, you are in a luck, as I am planning to upgrade them all...
