### ISSUE TITLE
Dashboard screen is blank after login

### ISSUE THREAD

**Issue by rafitur2** [Visual-Regression-Tracker/Visual-Regression-Tracker#408]
Hi,

The dashboard screen is blank after doing the login, can you please advise? 

![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/35892616/f1800680-329e-42bc-be04-2188daeafa0a)

![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/35892616/3f29ef47-76b0-4c7f-8d58-fa1162d081b4)

**Comment by rafitur2** [comment]
Adding Chrome Screenshots:
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/35892616/58d6d530-ac1c-4759-88d2-d434f1098acb)

![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/35892616/fd915b2a-7305-4d5c-8b19-7520d613f637)

**Comment by rafitur2** [comment]
+ More details:
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/35892616/c4d2d1c8-fa02-44e3-b8dc-eadaa4f79539)

**Comment by pashidlos** [comment]
there is `localhost` set for all urls 
is it available on http://localhost:8080/ and http://localhost:4200/api ?

**Comment by rafitur2** [comment]
Thanks @pashidlos . The issue has been resolved by running the below command:

./vrt-install.sh -a http://ilcepoc2457:9091/ -r http://ilcepoc2457:9092/
