### ISSUE TITLE
Compare screens even when the dimensions differ to some amount

### ISSUE THREAD

**Issue by paazmaya** [Visual-Regression-Tracker/Visual-Regression-Tracker#409]
It looks like the comparison diff is not generated when the baseline and the fresh screenshots differ in size, even for few pixels.

I would be curious to see if the smaller screen could be placed to some weighted position, and either the bigger screen cropped for the comparison time, or the smaller getting additional pixels on the sides. In either case, the sides are to be marked changed and hence getting higher amount of difference.
This would help in seeing if it is just the margin or padding that has changed in the target of the screenshot, assuming that the weighting happens to hit the right spot.

**Comment by pashidlos** [comment]
for `pixelmatch` and `lookSame` there is option in project config for that `Allow diff dimensions`
