### ISSUE TITLE
Agent for Robot Framework?

### ISSUE THREAD

**Issue by paazmaya** [Visual-Regression-Tracker/Visual-Regression-Tracker#411]
How about an agent for https://robotframework.org/?

Since it is using Python, I am not sure how trivial or complex would it be to use https://github.com/Visual-Regression-Tracker/sdk-python in the middle...

Any thoughts?

**Comment by pashidlos** [comment]
seems they have a way to write extensions for it 
don't know if it's possible to use it with sdk without any plugin
are you gonna use it?

**Comment by paazmaya** [comment]
It might come up to be useful, I will update when I have something to share...

**Comment by adam-hepner-np** [comment]
We have one that we're open sourcing right now. I'll ask colleague to share the repo as soon as it's ready.

**Comment by adam-hepner-np** [comment]
Here you go: https://github.com/NiceProjectPoland/robotframework-VRTLibrary

**Comment by pashidlos** [comment]
@adam-hepner-np thanks for the reference!
added in readme https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker
