### ISSUE TITLE
Frontend. Improve code quality in codacy

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#412]
Code score degraded to `B` https://app.codacy.com/gh/Visual-Regression-Tracker/frontend/dashboard?branch=master

**Comment by paazmaya** [comment]
While most of the almost 300 issues are about not finding imports (perhaps dependencies are not being installed at all), some of the other issues have been tackled within https://github.com/Visual-Regression-Tracker/frontend/pull/318

**Comment by pashidlos** [comment]
I wrote a message to them in support chat 
let's see if they point to the problem why it's happening

**Comment by pashidlos** [comment]
response from Codacy 
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/5182956/7b5216cf-5800-4089-87ac-fca69518140c)

**Comment by paazmaya** [comment]
ummm... Perhaps we could just disable that rule as it seems they install only certain packages of their own, not the project dependencies.

**Comment by pashidlos** [comment]
closed for https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/413
