### ISSUE TITLE
From Codacy to something else?

### ISSUE THREAD

**Issue by paazmaya** [Visual-Regression-Tracker/Visual-Regression-Tracker#413]
There seems to be constantly issues with Codacy, about not finding the dependencies used within our several repositories.

I have been using for similar activities SonarCloud.

Here are some search results for comparing those two and others:

* https://www.gartner.com/reviews/market/application-security-testing/compare/codacy-vs-sonarsource
* https://www.adservio.fr/post/best-tools-for-continuous-code-quality-and-automated-code-review

---

Problems with dependencies can be seen here https://app.codacy.com/gh/Visual-Regression-Tracker/frontend/pullRequest?prid=12222875

**Comment by paazmaya** [comment]
Now the backend repo has been setup at SonarCloud, at the readme shows two sets of badges for comparison
https://github.com/Visual-Regression-Tracker/backend

At the moment, rest of the repos are using the "automatic" config which does not evaluate code coverage.

Anyone wanting to continue for other repositories?

**Comment by pashidlos** [comment]
Codacy removed from `backend` and `frontend` project
