### ISSUE TITLE
Not able to add ignore area in VRT

### ISSUE THREAD

**Issue by RajaniKshirsagar** [Visual-Regression-Tracker/Visual-Regression-Tracker#419]
I am not able to add ignore area in VRT. Getting error as Bad Request Exception.
![IgnoreAreaError](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/0eadb013-167c-4d1a-aecd-371e54575ceb)

**Comment by pashidlos** [comment]
@RajaniKshirsagar could you share request that is sent and error from api service?

**Comment by RajaniKshirsagar** [comment]
@pashidlos 
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/0ab55b0b-4451-481d-8601-1f4ae63fe290)


Not getting any response:
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/5e8a0d67-4a42-43e7-9a20-99177cf9f934)

**Comment by pashidlos** [comment]
@RajaniKshirsagar it's not the right request 
try reproducing the issue and find request with error code 400
also it should be an error in docker logs for api container

**Comment by RajaniKshirsagar** [comment]
@pashidlos  I am getting this request with error code 400
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/d5b5f67b-22eb-4e8a-86d5-548e8d3d91f6)
 
Docker Logs:
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/dc6697a1-c384-430d-bc58-3895eb6e035c)

**Comment by pashidlos** [comment]
@RajaniKshirsagar what is the request payload?
it should be something like 
```
{"ids":["66e4dbe4-43d7-4616-bd86-03077eef2edb"],"ignoreAreas":[{"id":"1694440135732","x":85,"y":65,"width":54,"height":39}]}
```
what container versions are you using?

**Comment by RajaniKshirsagar** [comment]
@pashidlos I am getting below in headers tab:
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/b81a1667-56b5-4da3-a976-19f704cabd10)

and in preview tab, Its showing no contents available.
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/f4e0e185-d8a9-4480-915d-ad075ad47c35)

And the version is 24.0.5

**Comment by RajaniKshirsagar** [comment]
@pashidlos Can you please help me with this "Not able to add ignore area in VRT"?

**Comment by pashidlos** [comment]
@RajaniKshirsagar I cannot reproduce this issue
there is no such version as `24.0.5` 
use specific combination from release https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/releases

**Comment by RajaniKshirsagar** [comment]
@pashidlos It's Docker version 18.04. I don't know about container version.

**Comment by RajaniKshirsagar** [comment]
@pashidlos 
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/02975c46-6526-4a9b-8305-684492505618)

**Comment by RajaniKshirsagar** [comment]
@pashidlos 
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/65349879/2233c713-549a-4678-96da-57665c009fce)

**Comment by pashidlos** [comment]
@RajaniKshirsagar that is only ui version 
what is api and migration?
you could check it in .env file
is that something new after update?

**Comment by grafoxy** [comment]
Hi @pashidlos 
the same issue reproduced for me too.

>> what is api and migration?
It was the clear deploy of 5.0.2 version
visualregressiontracker/ui:5.0.2
visualregressiontracker/api:5.0.2

>>also need request payload that is sent in request
HAR file with request [vrt.zip](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/files/12698583/vrt.zip)

>>you could check it in .env file
VRT_UI_VERSION=5.0.2
VRT_API_VERSION=5.0.2
VRT_MIGRATION_VERSION=5.0.1

>>is that something new after update?
yes, I played some time ago with 4.x.x version and maybe with 5.0.0 but I not sure - this feature works perfectly

**Comment by pashidlos** [comment]
@grafoxy  I'm not able to reproduce it
could you provide steps?
this is how it works with 
```
VRT_UI_VERSION=5.0.2
VRT_API_VERSION=5.0.2
VRT_MIGRATION_VERSION=5.0.1
```
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/5182956/d3051c57-fbda-420c-8929-e58522752333

**Comment by grafoxy** [comment]
Steps: 
- open any test
- set ignore region
- save
 
Video - 

https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/1931175/f214d7e7-1cba-49ca-a44c-388cb21d6d0e

Docker logs - 
[docker-logs-vrt.txt](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/files/12712888/docker-logs-vrt.txt)

HAR - 
[docker-logs-vrt.txt](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/files/12712889/docker-logs-vrt.txt)

PS. I re-deploy project - but issue still present

**Comment by grafoxy** [comment]
@pashidlos Can I help with some additional logs that will speed up fixing this bug (this is a much-needed functionality)?

**Comment by pashidlos** [comment]
@grafoxy I managed to reproduce it 
going to fix it asap 
you could roll back to previous version meanwhile

**Comment by RajaniKshirsagar** [comment]
> @RajaniKshirsagar that is only ui version what is api and migration? also need request payload that is sent in request you could check it in .env file is that something new after update?

VRT_UI_VERSION=5.0.2
VRT_API_VERSION=5.0.2
VRT_MIGRATION_VERSION=5.0.1

**Comment by RajaniKshirsagar** [comment]
> @RajaniKshirsagar that is only ui version what is api and migration? also need request payload that is sent in request you could check it in .env file is that something new after update?

@pashidlos 

VRT_UI_VERSION=5.0.2
VRT_API_VERSION=5.0.2
VRT_MIGRATION_VERSION=5.0.1

I am using above versions of UI API and MIGRATION.

**Comment by pashidlos** [comment]
fixed in https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/releases/tag/5.0.2
