### ISSUE TITLE
  "apiKey": "DEFAULTUSERAPIKEYTOBECHANGED",

### ISSUE THREAD

**Issue by loocar** [Visual-Regression-Tracker/Visual-Regression-Tracker#432]
Hello :)
When I install either manually or with a quick setup "/vrt-install.sh" API key is generated each time through migration with: DEFAULTUSERAPIKEYTOBECHANGED
```
migration-1  | The user with the email "visual-regression-tracker@example.com" and password "123456" was created (if not changed before)
migration-1  | The Api key is: DEFAULTUSERAPIKEYTOBECHANGED
migration-1 exited with code 0
```
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/15063211/9aa6bc64-dc6d-457c-8b74-7e2d8f1d22eb)

Do I have to do anything extra?
Thanks for your help in advance :)

**Comment by pashidlos** [comment]
@loocar for basic service setup that is it 
now you could start integrating your tests with service

**Comment by aspenboy** [comment]
@pashidlos but the frontend returns "NetworkError when attempting to fetch resource.", so we can't really use the service. Also we're unable to change the API key.

We used to use pre-5.0 version and it worked fine, but for some reason we're unable to setup 5.0.2.

**Comment by pashidlos** [comment]
@aspenboy have you completed migration steps or trying to make a completely new instance?
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/releases/tag/5.0.0

**Comment by aspenboy** [comment]
@pashidlos no, we tried to setup from scratch.

It turned out that I forgot to update API url in `.env` - now everything works fine :) Thanks!
