### ISSUE TITLE
Bulk approve on feature branch end up in main branch history

### ISSUE THREAD

**Issue by groinder** [Visual-Regression-Tracker/Visual-Regression-Tracker#437]
I believe I have a bug that is hard to reproduce, but sometimes, somehow, a change approved on the feature branch ends up as a baseline for the main branch, before the feature branch is merged.

When I open the history of a baseline from the main branch, I can see that sometimes there is an image from a feature branch, and when I press "TEST RUN" it takes me to the run from that feature branch. I failed to reproduce this in a controlled environment so I'm just wondering if anybody found the same issue or how is that even possible. When this happens it messes up our tests, it drives me crazy.

VRT Version 5.0.2

**Comment by pashidlos** [comment]
@groinder could you try checking logs?
there should be entries about trying to autoApprove baseline from feature branch to make it main 
haven't seen this yet in my experience

**Comment by groinder** [comment]
I'm checking the logs now, I managed to find the entries for the particular testRun, here are the lines with this particular id:
```
vrt-api-2  | [32m[Nest] 18  - [39m06/21/2024, 6:38:23 AM [32m    LOG[39m [38;5;3m[TestRunsService] [39m[32mTry AutoApproveByPastBaselines testRun: 91084543-827d-4da1-ba7a-c7aa8c4518b3[39m
vrt-api-2  | [32m[Nest] 18  - [39m06/21/2024, 6:38:31 AM [32m    LOG[39m [38;5;3m[TestRunsService] [39m[32mTry AutoApproveByNewBaselines testRun: 91084543-827d-4da1-ba7a-c7aa8c4518b3[39m

vrt-api-2  | [95m[Nest] 18  - [39m06/21/2024, 7:46:59 AM [95m  DEBUG[39m [38;5;3m[TestRunsController] [39m[95mGoing to approve TestRuns: 0c8619da-e444-4ff4-87cb-dd9186c3c78d,d3a631ae-cc5b-4c08-80bf-14669883065a,bc0c62a3-78b4-47c4-9556-7bc5a7bf679a,eed5cd85-2a0a-4684-ba24-5fe9da3b0244,be6f3b9b-fa11-44c4-ae27-5dcfb9b9e851,a0485ccb-ca0e-4fde-9c1d-a3ae545c11fc,c8862744-0b61-468d-9d2f-ae00442bf79b,f14bfd1e-85d5-49c3-b180-ecdfbe5428de,7d59e05e-6d01-44c8-b24a-3158ceda48fd,fb5cbd0f-6491-466b-ad6c-b0162ef06b60,ea6a418d-9b07-472b-8aeb-1014ff1a800f,24371a4e-8396-4e9f-916d-630715d468f2,1324196e-eb15-48e4-ba1d-6d502610c069,35b5d472-14ae-487c-b203-49edb281af20,b9e04f25-b88d-439d-8d2e-4018d997ab36,a4229fce-a8fc-4234-b899-43a6e485ba16,82733f8c-4f7c-4c2a-b3dd-f548891d0373,5b574671-2b64-4112-aa11-c2e2376d4386,187eef2c-44f6-4d9f-891e-aa990ce99d82,64a08991-b23d-4ba3-a479-a76f051f1bc1,7bea8c56-23ad-40de-8a68-64bc0fd08c8f,2fe65a77-5c13-4f58-bb2d-1b71e1f53c7c,b27c15ef-4ebd-43bd-863d-06f3f806895b,ec2da483-f2c1-4c2b-bf53-e603cdae56cb,fe9a206e-e565-498b-99e1-3214712c49f5,fa4fbbdd-b5a7-45eb-8047-bea36aa0af28,cad4dc25-84c3-47b1-9cad-ef5b6266477d,fd0b8b7b-1fa9-459a-8aa5-b7429256e1f2,41cdc864-1f7e-450b-8c5e-0d5a8685eab6,55cd2f8f-a1a1-408c-aee7-bbb26add07e9,bebb5e0e-a594-42ca-abd3-28dc5d75acd8,9016fdc9-4bf4-4d80-903d-edc9e566bdf3,97156fcf-3e9c-4e4f-9a5e-6a354669cf9e,27971634-f9f1-443f-9ec1-bd44821a0463,f0616023-1341-4fc9-99b3-5d0d4f74debb,c042acc2-3594-4c39-b4e8-584a8339e75e,83311aa6-b384-45f2-852c-b9302c341b0d,8902764d-7900-403b-9892-9ed41c17e1a8,a5545fc9-23be-4ea5-8c13-171ec07d9855,1d30f257-b582-402d-adeb-94ecfe022274,91084543-827d-4da1-ba7a-c7aa8c4518b3,edd0c8e9-b6a3-47bd-9c9d-6aeddb688f87,1254641d-4750-4d69-93ed-de5b6c821c23,ba120392-39c7-4e01-bc95-564b3868da1b,2ba4da46-75f5-4863-a0d4-a9c97195c027[39m


vrt-api-2  | [32m[Nest] 18  - [39m06/21/2024, 7:47:19 AM [32m    LOG[39m [38;5;3m[TestRunsService] [39m[32mApproving testRun: 91084543-827d-4da1-ba7a-c7aa8c4518b3 merge: true autoApprove: false[39m
```

The last line is where this gets interesting, this is the exact time I can see in the history of the main branch, and the log says `merge: true` which is concerning to me since the branch with this test run was actually merged 4 days later.

**Comment by groinder** [comment]
I dug deeper into it, I can reproduce this now. Turns out this only happens if you use bulk-approve from the list. If I select all rows and then press the Approve button the new image ends up as a baseline in the main branch.
![image](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/assets/16709010/a086df9a-01e2-4b76-b86b-4b98b921a57b)

It seems like this particular piece of code is to blame: https://github.com/Visual-Regression-Tracker/frontend/blob/0cd8d6dbffc91c1afe599ef125ff0c01074742ac/src/components/TestRunList/BulkOperation.tsx#L49

Is this intended behavior and I just don't understand something or is this a bug? I fail to see the reason why the `isMerge` is set there.

**Comment by pashidlos** [comment]
@groinder good catch 
it used to be a getter for a `merge` property of `TestRun` to propagate the same in approve request 
https://github.com/Visual-Regression-Tracker/frontend/pull/318/files#diff-ae08eb1c01abd17c9fb1db13c79d2d1d6a75e419f24ac156facd5da446c0dfa1R50

**Comment by groinder** [comment]
I see, now it's missing the `.merge` part at the end. Seems like an easy fix.
