### ISSUE TITLE
backend behind basic auth does not work - Request cannot be constructed from a URL that includes credentials

### ISSUE THREAD

**Issue by monotek** [Visual-Regression-Tracker/Visual-Regression-Tracker#438]
If i put the VRT backend behind a basic auth proxy, and configure the REACT_APP_API_URL like `https://username:password@mydomain.com` i get the following error in the ui:

```
Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials: https://username:password@mydomain.com/projects
```

Any way to workaround this?

**Comment by pashidlos** [comment]
@monotek I guess it's due to deprecation of basic auth in url 
don't think you could workaround it as is without making it as a headers

**Comment by monotek** [comment]
How can i do it via headers?
Is there another ENV variable i could use?
Is there any documentation about it available?

**Comment by pashidlos** [comment]
@monotek it requires changes on frontend side, it's not implemented

**Comment by monotek** [comment]
Can you point out where in the Frontend?

Is there another way to protect the api? 

The api tokens seem only to protect the project but not stuff like user creation.

**Comment by pashidlos** [comment]
@monotek all private API are already protected with auth
use company VPN to completely restrict access to public as well

**Comment by monotek** [comment]
Thats kind of unfortunate.

Would be nice auth via header could be implemented.

Or at least an option to disable user registration.

**Comment by pashidlos** [comment]
@monotek yeah, disabling self registration could be an feature together with allowing admin users to create new ones
