### ISSUE TITLE
Full Page Capture Restriction

### ISSUE THREAD

**Issue by Andyruu** [Visual-Regression-Tracker/Visual-Regression-Tracker#439]
Currently trialing out Visual-Regression-Tracker for a new project and have been impressed so far. The only issue i've encountered is when trying to capture the full page on a particularly long web page the results will be only approx 2/3 of the page.

When watching the test via the runner I can see it start to take the screenshots and scroll along the page, after a few seconds it then simply stops.

Is there some timeout or underlying args that only provide vrt a set time to capture a page before stopping?

**Comment by pashidlos** [comment]
@Andyruu what agent/sdk you are using?
the thing is that taking screenshot is completely out of vrt control and depends on your automation tool 
you could double check it just by using screenshot function and see the same result that is send to vrt

**Comment by Andyruu** [comment]
@pashidlos Using the cypress agent, and you're completely correct, I get the same behaviour if I use the Cypress snapshot command directly.

I'll focus my efforts there instead. Thanks very much :)
