### ISSUE TITLE
Java. core-sdk. Rename Config class

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#50]
To bright more clarity with naming it should contain to what it belongs

Use instead: `VisualRegressionTrackerConfig`

to update:
- https://github.com/Visual-Regression-Tracker/sdk-java

**Comment by dp120291ssv** [comment]
this issue will be fixed

**Comment by pashidlos** [comment]
thanks for contributing!
