### ISSUE TITLE
Create Python SDK

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#59]

**Comment by dcrowe** [comment]
I'd like to give this a go. Are there any takers yet?

**Comment by pashidlos** [comment]
hi @dcrowe , it looks awesome! 
you could create PR against this repo https://github.com/Visual-Regression-Tracker/sdk-python

**Comment by dcrowe** [comment]
Can do. I've just got a few more tests to knock over.

**Comment by dcrowe** [comment]
Looks like you new first commit before i can fork and create a PR against the repo.

**Comment by pashidlos** [comment]
my bad, try now 
https://github.com/Visual-Regression-Tracker/sdk-python

**Comment by pashidlos** [comment]
@dcrowe you should get invitation with access to that repo

**Comment by dcrowe** [comment]
I've merged in initial support.

**Comment by pashidlos** [comment]
nice! 
could you share info how to publish new versions?

**Comment by pashidlos** [comment]
I'm not really into python but here I added example 
@dcrowe could you review it?
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/88

**Comment by dcrowe** [comment]
I'm new to publishing python pkgs myself, so I may not be doing it the best way but it seems pretty straight forward:
```
pipenv run clean
pipenv run build
pipenv run upload
```

If you set up a pypi.org account and give me your user name I can set you up as owner of the project.

**Comment by pashidlos** [comment]
I started thread in the team to keep some docs related to publishing 
feel free to add the what ever you think is important 
https://github.com/orgs/Visual-Regression-Tracker/teams/sdk-python

**Comment by pashidlos** [comment]
amazing, you made it real! 
closing the ticket and thank you for making the project better!

**Comment by dcrowe** [comment]
your account has been added to the pypi package
