### ISSUE TITLE
Variation details. Go to test button contains not formated date

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#67]
![1](https://user-images.githubusercontent.com/5182956/87044900-7ad3b880-c1f7-11ea-87e0-da5ce936be7d.png)

**Comment by shankybnl** [comment]
@pashidlos In case if this is still a valid issue and can be assigned, I would like to try it as my first issue.

**Comment by pashidlos** [comment]
@shankybnl assigned to you 
let me know if you need any help with initial set up!

**Comment by shankybnl** [comment]
Thank you @pashidlos. Could you please share the steps to reproduce this bug and the expected behavior?

**Comment by pashidlos** [comment]
precondition:
- at least one accepted baseline exists

steps:
- open homepage
- open project Variations
- open Variation history (direct link `/variations/details/<variation_id>`)

expected result:
- date is formatted the same way as on Project list page `/projects` 
<img width="906" alt="1" src="https://user-images.githubusercontent.com/5182956/97555469-d44b3780-19e0-11eb-862d-c25194972206.png">

**Comment by pashidlos** [comment]
gonna be released in `4.6.0`

thank you for contribution!
