### ISSUE TITLE
In documentation it says "diffTollerancePercent" was 1 

### ISSUE THREAD

**Issue by mwehnert** [Visual-Regression-Tracker/Visual-Regression-Tracker#89]
Hey guys,

your documentation says `diffTollerancePercent` default value was 1, when it is actually 0. This is stated wrong in several places (e.g.: [cypress agent docu](https://www.npmjs.com/package/@visual-regression-tracker/agent-cypress), [js sdk](https://www.npmjs.com/package/@visual-regression-tracker/sdk-js))

No big deal, but I was confused ;)

**Comment by pashidlos** [comment]
thanks for pointing out!

**Comment by pashidlos** [comment]
updated
