### ISSUE TITLE
SDK python. Add support for python3.6

### ISSUE THREAD

**Issue by dcrowe** [Visual-Regression-Tracker/Visual-Regression-Tracker#90]
python3.7 and 3.8 work out of the box.
python3.6 needs the dataclasses package to be installed before it works.

Goals:
* update the package meta-data to add this as a dependency for only python 3.6
* update the build process to test this.

**Comment by pashidlos** [comment]
moved ticket to main project

**Comment by dcrowe** [comment]
I've add a PR to tackle this: https://github.com/Visual-Regression-Tracker/sdk-python/pull/9

**Comment by pashidlos** [comment]
Well done! 
thank you for contribution!
