### ISSUE TITLE
Feature: Select area from screenshot and only check this area for regression

### ISSUE THREAD

**Issue by mwehnert** [Visual-Regression-Tracker/Visual-Regression-Tracker#91]
Currently there is the opportunity to exclude areas from the regression testing per image.

I suggest a second area selection option that limits the pixel matching to that area. This would help in focussing on special details.

I am aware, that I could as well take a smaller screenshot, but it would be much easier this way.

**Comment by pashidlos** [comment]
yeah, that could simplify current actions needed to limit area 

we will need to re-consider how we calculate difference also
as the `diffPercent` is calculated out of all image pixels count mb that could lower threshold for big images with small inclusion areas
does it make sense so far? 

I'm thinking of another algorithm of measuring the difference as straight percent out of total pixels is something but not how human sees
would like to introduce something like diff density that will fail the assertion if difference in concentrated in some place and not spread across all image that could be treated as noise

**Comment by priyankachaturvedi30** [comment]
Thanks @pashidlos for considering this feature. I think this would be a great add on if we have the capability to just compare specific areas and ignore rest while setting a baseline.

**Comment by priyankachaturvedi30** [comment]
@pashidlos: Sorry for rushing through this, but any planned release/duration until when we can expect this feature to be out?

**Comment by pashidlos** [comment]
@priyankachaturvedi30 I'll be honest with you saying that this is not the priority right now nor nearest future
I'll keep it in backlog for now
cropping image to needed areas is much preferred approach
