### ISSUE TITLE
SDK Python. Fix code style issues

### ISSUE THREAD

**Issue by pashidlos** [Visual-Regression-Tracker/Visual-Regression-Tracker#94]
https://app.codacy.com/gh/Visual-Regression-Tracker/sdk-python/issues?bid=19757392

**Comment by dcrowe** [comment]
I'm happy to take this one.

I added flake8 based linting, but it looks like Codacy uses Prospector and Bandit. I'll see if I can use the same tools for dev, and then resolve reported issues.

**Comment by pashidlos** [comment]
Awesome, assigned this to you

**Comment by dcrowe** [comment]
I've had a bit of a play with prospector/bandit/pylint running locally and the results don't match up with those from codacy.
I think, rather than provide local linting which doesn't match up, I'll remove the local linting and rely on codacy.

**Comment by pashidlos** [comment]
@dcrowe thanks for making project better!
